### ISSUE TITLE
x-code build error - error: 'init(activityIndicatorStyle:)' has been renamed to 'init(style:)'

### ISSUE THREAD

**Issue by arefay** [lukasgit/flutter_contacts#101]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

• No issues found!

Running on iOS emulator

I'm getting the following output with latest version: contacts_service: ^0.4.4

``Xcode's output:
↳
    /Users/dev/flutter/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.4.4/ios/Classes/SwiftContactsServicePlugin.swift:221:17: warning: initialization of immutable value 'contactViewController' was never used; consider replacing with assignment to '_' or removing it
                let contactViewController = CNContactViewController.init(forNewContact: nil)
                ~~~~^~~~~~~~~~~~~~~~~~~~~
                _
    /Users/dev/flutter/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.4.4/ios/Classes/SwiftContactsServicePlugin.swift:275:69: **error: 'init(activityIndicatorStyle:)' has been renamed to 'init(style:)'
                    let activityIndicatorView = UIActivityIndicatorView.init(activityIndicatorStyle: UIActivityIndicatorView.Style.gray)**
                                                                        ^    ~~~~~~~~~~~~~~~~~~~~~~
                                                                             style
    UIKit.UIActivityIndicatorView:5:12: note: 'init(activityIndicatorStyle:)' was obsoleted in Swift 4.2
        public init(activityIndicatorStyle style: UIActivityIndicatorView.Style)``

**Comment by lukasgit** [comment]
Fixed in PR https://github.com/lukasgit/flutter_contacts/pull/100
