### ISSUE TITLE
iOS and Samsung device contacts issue

### ISSUE THREAD

**Issue by mobiledev18** [lukasgit/flutter_contacts#107]
I am using the version from 0.3.10 to 0.4.5 but in iPhone6 the contact avatar display as color circle but not displaying the name. Please help on this previously it was working but after upgrading this issue occur then again I downgrade the library and now I am not able to see the contact list on iphone6.

Also on the Samsung A70 it not showing the contacts in the listing.

I am using this method to fetch the contacts of the phone
await ContactsService.getContacts(withThumbnails: false);

**Comment by lukasgit** [comment]
@sperochon related to your PR?

**Comment by sperochon** [comment]
@lukasgit   I don't know. The example app works fine on both my Android phone and my iPhone. It displays initials name in colored circles.

@mobiledev18  Do you reproduce this issue with the example app? If yes, please give some details about your Android and iOS versions. Open your app or the example Android or iOS app directly in Android Studio or Xcode, run it from here and see if there is an error message displayed in the console. Thanks.
