### ISSUE TITLE
iOS Contacts issue

### ISSUE THREAD

**Issue by mobiledev18** [lukasgit/flutter_contacts#109]
In ios I am getting this issue. Please help me on this . I am using contact_service 0.3.10 and permission hander 3.3.0

flutter: Permission Status :PermissionStatus.unknown
The operation couldn’t be completed. (CNErrorDomain error 102.)

**Comment by lukasgit** [comment]
@mobiledev18 sounds like you forgot to enable permissions:

https://github.com/lukasgit/flutter_contacts/blob/master/README.md#permissions

**Comment by iresharma** [comment]
> @mobiledev18 sounds like you forgot to enable permissions:
> 
> https://github.com/lukasgit/flutter_contacts/blob/master/README.md#permissions

as he said 

```
addconPer(String name, Map<String, dynamic> val) async {
		await SimplePermissions.requestPermission(Permission.ReadContacts).then((val) {});
		await SimplePermissions.requestPermission(Permission.WriteContacts).then((value) async {
			if(Platform.isAndroid) {
				if(await SimplePermissions.checkPermission(Permission.WriteContacts) && await SimplePermissions.checkPermission(Permission.ReadContacts)) {
					addCon(name, val);
				}
			}
			else {
				if(await SimplePermissions.getPermissionStatus(Permission.WriteContacts) == PermissionStatus.authorized && await SimplePermissions.getPermissionStatus(Permission.ReadContacts) == PermissionStatus.authorized) {
					addCon(name, val);
				}
			}
		});
	}
```

use this code after getting the simple permissions dependencies 
from [https://pub.dev/packages/simple_permissions#-readme-tab-](https://pub.dev/packages/simple_permissions#-readme-tab-)

```
dependencies:
  simple_permissions: ^0.1.9
```
