### ISSUE TITLE
Add a getContactById method

### ISSUE THREAD

**Issue by knyghtryda** [lukasgit/flutter_contacts#11]
There needs to be a method of retrieving an individual contact again by a contact ID instead of a query.  I'm trying to save a reference to a contact in my local DB and then pull up that contact again at a later date, but it doesn't look like this is possible at the moment.  Looking into this it looks like instead of using the contact_id that is currently stored you should be using the lookup key, which will persist through contact sync issues that may shuffle the IDs.  I'm currently working getting this to work for android, but will need some help getting the iOS code working.

**Comment by lukasgit** [comment]
@knyghtryda heads up, I am not the original author of this plugin. This plugin was written early on and has its limitations. The issue you are experiencing might be related to the limitations. We are working on re-writing a new plugin to replace this plugin from the ground up that is clean, secure, flexible, and easy to maintain.

Our resources are limited, but please feel free to contribute to the current plugin with your fixes / improvements. Please see the README for more information on how to contribute. Thanks!

**Comment by megid2** [comment]
@lukasgit There also seems to be the related limitation that every Contact is assumed to be only one RAW_CONTACT on Android, i.e. no aggregated contacts exists where contact id != raw contact id. This affects at least update and delete.
