### ISSUE TITLE
Cant compile release apk

### ISSUE THREAD

**Issue by krunduev** [lukasgit/flutter_contacts#116]
4 weeks ago all was ok
Now for  contacts_service: ^0.4.6  I get error for release apk
But flutter build appbundle work fine

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'contacts_service'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

The plugin contacts_service could not be built due to the issue above.

**Comment by krunduev** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.17.0 at /Users/krunduev/Projects/flutter
    • Framework revision e6b34c2b5c (12 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/krunduev/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6015.53

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (4 available)
    • emulator-5554       • emulator-5554                        • android-x86 • Android 4.1.2 (API 16) (emulator)
    • AOSP on IA Emulator • emulator-5556                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone (2)          • 00008020-001E41422199002E            • ios         • iOS 13.1.3
    • iPhone X            • A2DE4278-23BA-401A-B9D2-08AF984E0A3D • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

**Comment by maheshmnj** [comment]
@krunduev  were you able to resolve this issue ?

**Comment by raphaaugustosilva** [comment]
This is happening with my project too. Is there any workaround to manage it?

**Comment by raphaaugustosilva** [comment]
I could fix it by upgrading gradle version from 3.5.0 to 3.5.0

classpath 'com.android.tools.build:gradle:3.5.0'  =>  updated to  =>. classpath 'com.android.tools.build:gradle:3.5.4'
