### ISSUE TITLE
FormatException: Invalid date format

### ISSUE THREAD

**Issue by YaroslavKushnir94** [lukasgit/flutter_contacts#119]
When the user fills birthday information of contact, he can skip year and sets only month and day.
Unfortunately, the library cannot parse such format of date, as a result we lose this information.

More information on this screenshot: 

<img width="1387" alt="Screenshot 2020-05-22 at 17 15 55" src="https://user-images.githubusercontent.com/33039202/82677136-380e4f00-9c50-11ea-9f5e-62b4e659c3ec.png">

It would be great add opportunity to handle such format of date.

**Comment by suztomo** [comment]
@YaroslavKushnir94 Did you get any workaround on this issue?
