### ISSUE TITLE
Contact Birthday Data

### ISSUE THREAD

**Issue by runedrune** [lukasgit/flutter_contacts#12]
Would it be possible to add grabbing a contacts birthday data to this plugin?

**Comment by lukasgit** [comment]
@runedrune heads up, I am not the original author of this plugin. This plugin was written early on and has its limitations. The issue you are experiencing might be related to the limitations. We are working on re-writing a new plugin to replace this plugin from the ground up that is clean, secure, flexible, and easy to maintain.

Our resources are limited, but please feel free to contribute to the current plugin with your fixes / improvements. Please see the README for more information on how to contribute. Thanks!

**Comment by PaddyBadger** [comment]
Thanks @lukasgit - any idea of the eta on the re-write to help us decide on contribution v waiting?

**Comment by ZaraclaJ** [comment]
I made a pull request for this. I hope it will be accepted

**Comment by PaddyBadger** [comment]
🤞 incredible! Thank you

**Comment by lukasgit** [comment]
@ZaraclaJ thanks for your PR! Committed in release 0.3.6 (just published)

**Comment by lukasgit** [comment]
@PaddyBadger ^^ (thanks for your patience!)

**Comment by PaddyBadger** [comment]
Incredible, thank you so much!
