### ISSUE TITLE
Suggestions on how to make it faster?

### ISSUE THREAD

**Issue by andressilvac** [lukasgit/flutter_contacts#123]
Hi!
Thanks for the plugin!

Do you have any suggestions on how to optimize it? It is currently taking too long to run the ContactsService.getContacts().

Thanks!

**Comment by sanjidbillah** [comment]
horrible problem -_-

**Comment by palexs** [comment]
I assume the plugin should attempt batched contacts load.

**Comment by palexs** [comment]
There's a similar issue, btw:  https://github.com/lukasgit/flutter_contacts/issues/123

**Comment by palexs** [comment]
In the meantime I will try to migrate to https://github.com/SunnyApp/flutter_contact as it tries to be memory and cpu friendly. This plugin avoids loading your entire address book into memory, but rather provides a couple ways to access all contacts.
