### ISSUE TITLE
how to get particular mobile number?

### ISSUE THREAD

**Issue by aTeamSolace** [lukasgit/flutter_contacts#135]
so i'm getting all information about that contact but not getting mobile number of that particular number

**Comment by marcomsl** [comment]
You need to get the contact list like this:
`List<Contact> = (await ContactsService.getContacts()).toList()`

Then you need to get the contact you want to use. In a listview for example like this:
`Contact contact = _contactsList[index];`

Now you have to get the 'phones' value from this contact as list with 'Item' as type:
`List<Item> phonesList = (contact.phones).toList();`

At the end you simply get the value of this item:
`String number = phonesList[0].value;`
