### ISSUE TITLE
Access Contact based on Phone number

### ISSUE THREAD

**Issue by vishnureddys** [lukasgit/flutter_contacts#138]
Hey, 
First of all, thanks for the aswesome package.

I just wanted to know if there is any way to access the name of a contact by knowing only the number.

**Comment by zackattack73** [comment]
Use this : Iterable<Contact> contacts = await ContactsService.getContactsForPhone("YourPhoneNumber");

**Comment by vishnureddys** [comment]
Oh, thanks. It works. This has to be shown in the documentation.
Or is it already there and I missed it? Either way, thank you.
