### ISSUE TITLE
How to choose default contact storage in phonebook?

### ISSUE THREAD

**Issue by prakhar-goel** [lukasgit/flutter_contacts#141]
By default, the contact is getting saved in the "Device" storage for the phonebook. Usually people like to save new contacts in their google account to get auto synced.

How can I choose Phonebook's Contact storage while using this plugin?

<img src="https://user-images.githubusercontent.com/1198834/87953326-84e39a00-cac8-11ea-8b13-1ce59c572ae4.jpeg" height="700">

**Comment by AmG2000** [comment]
I also have the same issue. Did you find a fix for this?
