### ISSUE TITLE
getContactsForPhone for partial searches

### ISSUE THREAD

**Issue by ghenry** [lukasgit/flutter_contacts#147]
Hi all,

I've been looking at the underlying plugin but can't see if this support partial searches for type ahead completion.

It only seems to return a contact if the whole number matches.

**Comment by vikalpnagar** [comment]
Replacing method getCursorForPhone inside ContactsServicePlugin.java with the below code worked for me at least for android.
private Cursor getCursorForPhone(String phone) {
    if (phone.isEmpty())
      return null;

    String selection = "(" + ContactsContract.Data.MIMETYPE + "=? OR " + ContactsContract.Data.MIMETYPE + "=? OR "
            + ContactsContract.Data.MIMETYPE + "=? OR " + ContactsContract.Data.MIMETYPE + "=? OR "
            + ContactsContract.Data.MIMETYPE + "=? OR " + ContactsContract.Data.MIMETYPE + "=? OR "
            + ContactsContract.Data.MIMETYPE + "=? OR " + ContactsContract.RawContacts.ACCOUNT_TYPE + "=?" + ")";
    ArrayList<String> selectionArgs = new ArrayList<>(Arrays.asList(CommonDataKinds.Note.CONTENT_ITEM_TYPE, Email.CONTENT_ITEM_TYPE,
            Phone.CONTENT_ITEM_TYPE, StructuredName.CONTENT_ITEM_TYPE, Organization.CONTENT_ITEM_TYPE,
            StructuredPostal.CONTENT_ITEM_TYPE, CommonDataKinds.Event.CONTENT_ITEM_TYPE, ContactsContract.RawContacts.ACCOUNT_TYPE));
    if (phone != null) {
      selectionArgs = new ArrayList<>();
      selectionArgs.add(phone + "%");
      selection = Phone.NUMBER + " LIKE ?";
    }
    return contentResolver.query(ContactsContract.Data.CONTENT_URI, PROJECTION, selection, selectionArgs.toArray(new String[selectionArgs.size()]), null);
  }

I haven't tested it thoroughly. Be careful.

**Comment by ghenry** [comment]
Thanks! A PR?
