### ISSUE TITLE
Error: MissingPluginException(No implementation found for method getContacts

### ISSUE THREAD

**Issue by giacomok** [lukasgit/flutter_contacts#150]
Hi,  
I am not able to use this plugin.  
I just installed and import the package, and I get this error:

`Error: MissingPluginException(No implementation found for method getContacts on channel github.com/clovisnicolas/flutter_contancts)`

I know this is an old branch, but I do not know howto use the new one.

**Comment by jstride** [comment]
How did you solve the issue? I have this too.

**Comment by giacomok** [comment]
I just followed the installation steps, cleaned the project and the error disappeared

**Comment by tenshis** [comment]
What did you do differently from the first time then?

**Comment by echb** [comment]
i had face the same issue, the problem was i needed OS permission (i used permission_handler) like the docs said, hope this helped @tenshis
