### ISSUE TITLE
Add fromJson and ToJson methods to read/write contacts onto Firebase Firestore

### ISSUE THREAD

**Issue by archit-aggarwal** [lukasgit/flutter_contacts#162]
Please add Json serializations to handle Json parsing. If I add contact as contact.toMap() to firestore, it gives unhandled exception when contacts have avatar.

**Comment by archit-aggarwal** [comment]
Exception is : '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'

**Comment by apackin** [comment]
There's definitely interest in this addition: https://stackoverflow.com/questions/68785393/problem-serializing-a-list-of-objects-in-flutter-and-saving-it-using-shared-pref/70702483?noredirect=1#comment125004872_70702483.

Should be an easy PR if the community is interested.
