### ISSUE TITLE
Fetching contact groups

### ISSUE THREAD

**Issue by easazade** [lukasgit/flutter_contacts#169]
Users can define different groups of contacts on their phones like (family, coworkers, friends and etc) and assign contacts to those groups. 

It will be great if we can fetch groups of contacts that user has defined on his/her phone.

**Comment by easazade** [comment]
this is one feature that is used a lot and really needed by the flutter community.

**Comment by easazade** [comment]
would have fixed this. if I only knew how to do IOS native programming.

**Comment by Josimarcsilva** [comment]
That would really be great!
It could have the ability to create groups of contacts.
Functionalities:
Create Groups of Contacts;
Read Contacts in Contact Groups;
Record Contacts in Contact Groups;

**Comment by lukasgit** [comment]
Looking for help... anyone is welcome to submit a workable PR to staging branch. Thanks

**Comment by abhinavsingh** [comment]
I am wondering if this in the pipelines somewhere or at-least in the roadmap.   If not, please update the issue accordingly so that someone in the community can take it forward.  Thank you!!!
