### ISSUE TITLE
wrong orientation when calling ContactsService.addContact with avatar

### ISSUE THREAD

**Issue by dvdlg** [lukasgit/flutter_contacts#174]
I am using contacts_service 0.4.6 and I am trying to add a new contact with an avatar.
The contact is successfully added, but the avatar is rotated.
(I tested it on android device)
the relevant code in my app is:
```
ContactsService.addContact(
  Contact(
    givenName: firstName.text,
    familyName: lastName.text,
    phones: [Item(label: 'mobile', value: phoneNumber)],
    avatar: (await NetworkAssetBundle(Uri.parse(imageURL)).load(imageURL)).buffer.asUint8List(),
  ),
);
```
when I use the same Uint8List object to present an image in the app itself, it is in the correct orientation, therefore I am sure that the problem is in the contacts_service library.

**Comment by SlavisDEV** [comment]
I have the same issue. Any updates?
