### ISSUE TITLE
Can't update contacts

### ISSUE THREAD

**Issue by Snowworm3000** [lukasgit/flutter_contacts#182]
I am trying to update a contact using `ContactsService.updateContact(contact);` however there is no change to the contacts.
I have actually tried using the `ContactsService.addContact(contact);` method which when I change the birthday it adds the new birthday but keeps the original as well, it also clones every other part of the contact and it doensn't happen with the name.
I am not recieving any errors on the console, but nothing is changing.
By the way I have checked the contact object that I am passing as the value and it seems correct I will post the values of it here.

`androidAccountName:"I am censoring this part"

androidAccountType:AndroidAccountType (AndroidAccountType.google)

androidAccountTypeRaw:"com.google"

avatar:_Uint8ArrayView ([])

birthday:DateTime (2000-05-20 00:00:00.000)

company:null

displayName:"Changed"

emails:MappedListIterable (())

familyName:"Test"

givenName:"Brian"

identifier:"200"

jobTitle:null

middleName:null

phones:MappedListIterable ((Instance of 'Item', Instance of 'Item'))

postalAddresses:MappedListIterable (())

prefix:null

suffix:null

hashCode:134729209

runtimeType:Type (Contact)`

Please could someone help me or let me know if this is an issue with the package.
Thanks.

**Comment by scriptshadow** [comment]
I am having the same problem as you.

**Comment by Alloco225** [comment]
Same problem here too.

**Comment by Snowworm3000** [comment]
Oh well, at least it's not just me.
I ended up writing my own native code to bring up the picked contact in android. It won't work in iOS though.
This should still be fixed though, I'm suggesting an alternative to everyone else.

**Comment by scriptshadow** [comment]
@Snowworm3000 Your application is intended for Android only ?

**Comment by Alloco225** [comment]
@Snowworm3000 writing native code is the alternative you're suggesting ?

**Comment by Snowworm3000** [comment]
> 
> 
> @Snowworm3000 Your application is intended for Android only ?

Yes it is, but it can be done in ios too. It's just that my app will only be on google play.

**Comment by Snowworm3000** [comment]
> 
> 
> @Snowworm3000 writing native code is the alternative you're suggesting ?

It's not ideal but this issue hasn't been fixed yet, so your only option right now is to write the code yourself to do what this package should be doing.
