### ISSUE TITLE
ArgumentError (Invalid argument(s) (input): Must not be null)

### ISSUE THREAD

**Issue by Development4A** [lukasgit/flutter_contacts#185]
![Screen Shot 2021-01-16 at 2 33 15 PM](https://user-images.githubusercontent.com/47068862/104824669-a2d85000-5808-11eb-921a-f4e28f632d22.png)
The issue has not appeared until the last Flutter update.

Line of code that invokes the error:
    List<Contact> contacts = (await ContactsService.getContacts(withThumbnails: false)).toList();  

Tried on simulator and two iPhones, the same issue appeared. I'm using an iMac with the current version of Visual Studio and iOS.

ContactsService.getContactsForEmail works but is not what I need.

Thank you for your help,
Jeff

**Comment by lexprimost** [comment]
hi , i have the same issues at the moment, any news ?

**Comment by Development4A** [comment]
I have received no response.

**Comment by Development4A** [comment]
NO one has contacted me.

    On Tuesday, January 19, 2021, 4:16:57 PM PST, Primaël Owald Lebrun <notifications@github.com> wrote:  
 
 


hi , i have the same issues at the moment, any news ?

**Comment by wdelawed** [comment]
I have the same issue
on flutter 1.22.6

**Comment by ABmamunHoneybee** [comment]
Sometimes really I realize Reactnative is more than better form Flutter.
so many bugs occurred when we did a project for a client. I fuck u all google flutter developers.
