### ISSUE TITLE
iOS module 'contacts_service' not found @import contacts_service;

### ISSUE THREAD

**Issue by web75018** [lukasgit/flutter_contacts#186]
Hi Guys
im getting this during the iOS build :

**module 'contacts_service' not found
@import contacts_service;**

- Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64)
- Xcode - develop for iOS and macOS (Xcode 11.3)

Thank you

**Comment by arsalanImtiaz455** [comment]
I am also facing this issue need help.
<img width="302" alt="Screenshot 2021-07-07 at 8 01 45 PM" src="https://user-images.githubusercontent.com/68081096/124783024-2bd17800-df5e-11eb-9496-c6462ddaa683.png">

**Comment by vishweshsoni** [comment]
same issue

**Comment by vantutrieu97** [comment]
I faced same issue :(
