### ISSUE TITLE
Not Compatible with AndroidX

### ISSUE THREAD

**Issue by ardeshir-33033** [lukasgit/flutter_contacts#190]
Hello, I want to build an app using flutter_contacts but it is throwing this error when I try to build
``
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':contacts_service'.
> Could not resolve all artifacts for configuration ':contacts_service:classpath'.
   > Could not find gradle.jar (com.android.tools.build:gradle:3.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.2/gradle-3.3.2.jar
   > Could not find builder.jar (com.android.tools.build:builder:3.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.2/builder-3.3.2.jar
   > Could not find tracker.jar (com.android.tools.analytics-library:tracker:26.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.3.2/tracker-26.3.2.jar
   > Could not find shared.jar (com.android.tools.analytics-library:shared:26.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/26.3.2/shared-26.3.2.jar
   > Could not find crash.jar (com.android.tools.analytics-library:crash:26.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.3.2/crash-26.3.2.jar
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.3.2/lint-gradle-api-26.3.2.jar
   > Could not find gradle-api.jar (com.android.tools.build:gradle-api:3.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle-api/3.3.2/gradle-api-3.3.2.jar
   > Could not find databinding-compiler-common.jar (androidx.databinding:databinding-compiler-common:3.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/3.3.2/databinding-compiler-common-3.3.2.jar
   > Could not find manifest-merger.jar (com.android.tools.build:manifest-merger:26.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/manifest-merger/26.3.2/manifest-merger-26.3.2.jar
   > Could not find sdk-common.jar (com.android.tools:sdk-common:26.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.3.2/sdk-common-26.3.2.jar
   > Could not find builder-test-api.jar (com.android.tools.build:builder-test-api:3.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.3.2/builder-test-api-3.3.2.jar
   > Could not find ddmlib.jar (com.android.tools.ddms:ddmlib:26.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.3.2/ddmlib-26.3.2.jar
   > Could not find sdklib.jar (com.android.tools:sdklib:26.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.3.2/sdklib-26.3.2.jar
   > Could not find layoutlib-api.jar (com.android.tools.layoutlib:layoutlib-api:26.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/26.3.2/layoutlib-api-26.3.2.jar
   > Could not find dvlib.jar (com.android.tools:dvlib:26.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/dvlib/26.3.2/dvlib-26.3.2.jar
   > Could not find repository.jar (com.android.tools:repository:26.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/repository/26.3.2/repository-26.3.2.jar
   > Could not find common.jar (com.android.tools:common:26.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/common/26.3.2/common-26.3.2.jar
   > Could not find builder-model.jar (com.android.tools.build:builder-model:3.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-model/3.3.2/builder-model-3.3.2.jar
   > Could not find protos.jar (com.android.tools.analytics-library:protos:26.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.3.2/protos-26.3.2.jar
   > Could not find apkzlib.jar (com.android.tools.build:apkzlib:3.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/3.3.2/apkzlib-3.3.2.jar
   > Could not find apksig.jar (com.android.tools.build:apksig:3.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.3.2/apksig-3.3.2.jar
   > Could not find annotations.jar (com.android.tools:annotations:26.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.3.2/annotations-26.3.2.jar
   > Could not find databinding-common.jar (androidx.databinding:databinding-common:3.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/3.3.2/databinding-common-3.3.2.jar
   > Could not find baseLibrary.jar (com.android.databinding:baseLibrary:3.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.3.2/baseLibrary-3.3.2.jar
> Could not get unknown property 'android' for project ':contacts_service' of type org.gradle.api.Project.

after this error, this line comes up 

The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.

and it seems many packages cannot work fine with this issue like speech_to_text.

any thoughts?

**Comment by danielnordh** [comment]
I often get similar warnings, and while not a fix I am normally able to build after cleaning, from terminal:
`cd android`
`./gradlew clean`
`cd ..`
`flutter run`

**Comment by lukasgit** [comment]
Fixed in #208 and new build 0.6.0 published today
