### ISSUE TITLE
Why does getContacts return an Iterable instead of a List?

### ISSUE THREAD

**Issue by andrewackerman** [lukasgit/flutter_contacts#195]
The Android-side Java code sends its data across the method channel as an `ArrayList` and the iOS-side Swift sends its data as an `Array`. According to [method channel documentation](https://flutter.dev/docs/development/platform-integration/platform-channels), both of these types are mapped to the Dart type `List`. So why are the `getContacts` and other related methods returning the data as `Iterable`? It's extremely arbitrary, not to mention inconvenient for people using your package to have to perform what would otherwise be a redundant manual conversion of the `Iterable` back to a `List`.

**Comment by sgehrman** [comment]
I came here to say the same thing.

**Comment by lukasgit** [comment]
@andrewackerman @sgehrman dates back to the original author of this plugin.  Contributions are welcomed.. please submit a workable PR to staging branch. Thanks

**Comment by Abion47** [comment]
I mean I can put in a PR for this, but... it's literally just changing `Iterable` to `List` in a couple of places, Ctrl+F style. It wouldn't even require changing any tests since `List` is fully compatible with `Iterable` in every context.

**Comment by deakjahn** [comment]
Let's reopen this. `Iterable` is absolutely unusual in this case and causes a lot of trouble (eg. with `FutureBuilder`).

**Comment by lukasgit** [comment]
> I mean I can put in a PR for this, but... it's literally just changing `Iterable` to `List` in a couple of places, Ctrl+F style. It wouldn't even require changing any tests since `List` is fully compatible with `Iterable` in every context.

@Abion47 yes I know but at the moment I have zero time to work on flutter_contacts so your PR (and testing) will help greatly.. thanks!

**Comment by lukasgit** [comment]
Thanks for the help. Sync'd with master and published https://github.com/lukasgit/flutter_contacts/pull/254
