### ISSUE TITLE
Android 11: FormOperationErrorCode.FORM_COULD_NOT_BE_OPEN

### ISSUE THREAD

**Issue by ghenry** [lukasgit/flutter_contacts#196]
Hi all,

Since Android 11 upgrade on my Samsung s10e, I can't seem to use these any more:

```
ContactsService.openContactForm()
ContactsService..openDeviceContactPicker()
```

same on simulators. Android 10 and below are fine.

Thanks.

**Comment by lukasgit** [comment]
@ghenry let's move this discussion to #197
