### ISSUE TITLE
Deprecation in Android 11 stops the plugin from working

### ISSUE THREAD

**Issue by andrlange** [lukasgit/flutter_contacts#197]
Due to the deprecation of AsyncTask on Android 11 the plugin is not working anymore

[deprecation] Registrar in PluginRegistry has been deprecated
[deprecation] AsyncTask()
[deprecation] executeOnExecutor
[deprecation] doInBackground
[deprecation] onPostExecute(Result)

**Comment by ghenry** [comment]
Same https://github.com/lukasgit/flutter_contacts/issues/196

**Comment by arjenfvellinga** [comment]
and #204 I think

**Comment by ghenry** [comment]
Just reading https://www.simplifiedcoding.net/android-asynctask/ and looking how to replace it at https://github.com/lukasgit/flutter_contacts/blob/master/android/src/main/java/flutter/plugins/contactsservice/contactsservice/ContactsServicePlugin.java#L421

Not done this before, but will have a go.

**Comment by ghenry** [comment]
> Due to the deprecation of AsyncTask on Android 11 the plugin is not working anymore
> 
> [deprecation] Registrar in PluginRegistry has been deprecated
> [deprecation] AsyncTask()
> [deprecation] executeOnExecutor
> [deprecation] doInBackground
> [deprecation] onPostExecute(Result)

@andrlange which bits aren't working for you? I still see all contacts but can't use these:

```
ContactsService.openContactForm()
ContactsService..openDeviceContactPicker()
```

but I they are not related to `GetContactsTask` or `GetAvatarsTask` which use `AsyncTask`

**Comment by andrlange** [comment]
By switching on debug logging I even can't get the app build for Android anymore.

I would recommend to transform the Android Java part to Kotlin so Kotlin Coroutines would replace Java Async Tasks. Most of the code should be translated quite simple because it's most work is mapping.

**Comment by lukasgit** [comment]
@Faiyyazauxy could you look into this?

**Comment by Faiyyazauxy** [comment]
Okay i will try to convert it and if done i will create a PR

**Comment by jasonkaruza** [comment]
Any updates on fixing this? App keeps crashing when trying to get contacts from device.

**Comment by lukasgit** [comment]
@Faiyyazauxy thanks for the update, which staging PR are you referring to?

**Comment by ghenry** [comment]
> The contact add & edit falls into such categories. So there is a new requirement where we need to write a tag in manifest mentioning the permission for such special permission. Check out this link for more explaination : https://developer.android.com/training/package-visibility/use-cases
> 


What are the manifest queries for contacts?

I recently had to do this:

```
    <!-- AppAuth and url_launcher targeting API 30 or new (Android 11 or newer) -->
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" />
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.APP_BROWSER" />
            <data android:scheme="https" />
        </intent>
        <!-- url_launcher only -->
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="mailto" />
        </intent>
    </queries>
```

but presume the native code needs updating to check for these too as per https://developer.android.com/training/package-visibility/use-cases

**Comment by ghenry** [comment]
Going to test this now as I see there is a new release (0.6.1)
