### ISSUE TITLE
Empty array returned on iOS 13

### ISSUE THREAD

**Issue by darrylong** [lukasgit/flutter_contacts#2]
The following method in iOS 13 returns an empty array.
`ContactsService.getContacts()`

In iOS 13, developers are unable to access the notes portion of contacts. I was thinking that this could be the cause of the problem.

**Comment by lukasgit** [comment]
@uohziyoam what was the reason for referencing issue #5 ?

**Comment by lukasgit** [comment]
@darrylong what are the results you get when you run the example app included in the `example/` folder?

**Comment by olegkrutskih** [comment]
@lukasgit no result.
1. Start example app
2. Showing permission request
3. I'm allow
4. Empty page
5. Add contact button is work, contacts creating, page is empty.

Can I collect some more data for you?

**Comment by lukasgit** [comment]
@olegkrutskih recent updates were pushed just now. Please try again and let me know if things are working for you now. Thanks!

**Comment by olegkrutskih** [comment]
> @olegkrutskih recent updates were pushed just now. Please try again and let me know if things are working for you now. Thanks!

Super!
It works!

**Comment by dvlj** [comment]
Flutter (Channel stable, v1.9.1+hotfix.2)

worked!  0.3.4 confirmed!

**Comment by kroksys** [comment]
Have exact same problem using a **real device**.
Using example I'm getting an **empty array of contacts**. 
**It works using Android and iOS Simulator.**

iOS 13

[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

**Comment by sivanookalatt** [comment]
Hello @lukasgit is there any way we can get the '**note**', while creating or updating the contact. Earlier we were using **note** in **0.2.8** but its no longer available now.

**Comment by lukasgit** [comment]
@kroksys and @sivanookalatt Apple recently announced iOS 13 will no longer support access to the Notes field:

https://techcrunch.com/2019/06/05/with-ios-13-apple-locks-out-apps-from-accessing-users-private-notes-in-contacts/

**Comment by lukasgit** [comment]
@olegkrutskih and @dvlj ... great to hear it's working for you now!

**Comment by vishwajit76** [comment]
> @lukasgit no result.
> 
> 1. Start example app
> 2. Showing permission request
> 3. I'm allow
> 4. Empty page
> 5. Add contact button is work, contacts creating, page is empty.
> 
> Can I collect some more data for you?

i have same problem in version 0.4.6
