### ISSUE TITLE
Definition of birthday is wrong ?

### ISSUE THREAD

**Issue by BillDietrich** [lukasgit/flutter_contacts#201]
[I'm new to this, I might be totally wrong.]

contacts.birthday is defined as a single field, but in the standard Contacts app on my Android 9 phone it seems there is a collection Dates of which Birthday is one member.

Setting contacts.birthday through contacts_service doesn't work; the new value does not appear in the Contacts app.

I've tried versions 0.4.6 and 0.5.0-nullsafety.0

**Comment by BillDietrich** [comment]
Please don't auto-close this issue.

**Comment by BillDietrich** [comment]
Please don't close this issue.

**Comment by BillDietrich** [comment]
Please don't close this issue.

**Comment by hieutv-dng** [comment]
Need some help fix this issue, please don't close this issue

**Comment by BillDietrich** [comment]
Please don't close this issue.

**Comment by BillDietrich** [comment]
Please don't close this issue.

**Comment by BillDietrich** [comment]
Please don't auto-close.
