### ISSUE TITLE
Are there standard labels for collections such as Phone ?

### ISSUE THREAD

**Issue by BillDietrich** [lukasgit/flutter_contacts#202]
I have a phone running Android 9.

Using 0.4.6, I found that if my app created an item in the Phone collection with label "private", the new phone number did not show up in my phone's standard Contacts app.  If I created an item with label "other", the new number did show up tagged s "Other".

Now with 0.5.0-nullsafety.0, this seems to have changed.  If my app creates an item labeled "other", the number does not appear in the Contacts app.  If it creates an item labeled "custom", the number shows up in the Contact app tagged as "Home".

Is there a standard set of labels ?  Please document it.  Thanks.

**Comment by BillDietrich** [comment]
Please don't close this issue.

**Comment by BillDietrich** [comment]
Please don't close this issue.

**Comment by BillDietrich** [comment]
Please don't auto-close this issue.

**Comment by BillDietrich** [comment]
Please don't auto-close this issue.

**Comment by lukasgit** [comment]
Hi there!  This is a community project (my time is very limited, sorry).  Please feel free to contribute your PR for review... thanks!

**Comment by BillDietrich** [comment]
Please don't auto-close.
