### ISSUE TITLE
ContactsServicePlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by virajdoshi11** [lukasgit/flutter_contacts#204]
I am using `contacts_service` version 0.4.6

The problem is when I created an apk for my project there was one warning stating that `ContactsServicePlugin.java uses or overrides a deprecated API`.
Also I was using `permission_handler` package and there was a similar warning for that as well.

My flutter version is 2.0.1 in stable channel

there is no minimal code to regenerate that error, I guess this happens with any project

**Comment by virajdoshi11** [comment]
Did anyone solve this issue ? @lukasgit

**Comment by arjenfvellinga** [comment]
For me, it fails on the line `if (intent.resolveActivity(context.getPackageManager()) != null) {` in

```
    void startIntent(Intent intent, int request) {
      if (this.activityPluginBinding != null) {
        if (intent.resolveActivity(context.getPackageManager()) != null) {
          activityPluginBinding.getActivity().startActivityForResult(intent, request);
        } else {
          finishWithResult(FORM_COULD_NOT_BE_OPEN);
        }
      } else {
        context.startActivity(intent);
      }
    }
```

**Comment by lukasgit** [comment]
@virajdoshi11 @arjenfvellinga my plate is full at the moment... can either of you submit a PR for this issue?

**Comment by AntonyLeons** [comment]
@arjenfvellinga please provide example code as I have my apps running on android 11 and I view and add to the contacts in this app, please be aware contacts permission must be granted or errors will occur

**Comment by arjenfvellinga** [comment]
@AntonyLeons 

I'm sure the contact permission is granted.

But the function I call is `openExistingContact`, so maybe view and add works, but edit don't on Android 11? There is no specific code to share other than:
```
  Future<void> edit(domain.Contact contact) async {
    _requestPermission(permission: Permission.contacts);

    await ContactsService.openExistingContact(contact.toThirdPartyEntity());
  }
```

**Comment by aktarulahsan** [comment]
my issue  is 
Note: /Users/app-dev/.pub-cache/hosted/pub.dev/contacts_service-0.6.3/android/src/main/java/flutter/plugins/contactsservice/contactsservice/ContactsServicePlugin.java uses or overrides a deprecated API.

**Comment by R-ia** [comment]
have you found any solution to this same is happening with me
