### ISSUE TITLE
Adding Date Added/Created

### ISSUE THREAD

**Issue by Apperfect** [lukasgit/flutter_contacts#205]
Is it possible to extract the date when the contact was created? If not, could this be added as a feature request? I found the following guidance on how this could be pulled on iOS: https://stackoverflow.com/questions/32786677/getting-date-a-contact-was-added-to-the-address-book-in-swift-2-ios-9

**Comment by lukasgit** [comment]
@Apperfect my plate is full at the moment... can you submit a PR for this issue?
