### ISSUE TITLE
Not working on Samsung Devices

### ISSUE THREAD

**Issue by mayurnile** [lukasgit/flutter_contacts#209]
The plugin and code works very well on any other android device with any version of Android and as well as iOS. but on Samsung Devices with One UI the contacts are not getting fetched.

**Comment by lukasgit** [comment]
@mayurnile try latest build 0.6.0 pushed today

**Comment by mayurnile** [comment]
No luck, it's still not working on Samsung Devices neither it is working on iOS12+, is there any extra setup we need to do ?

**Comment by lukasgit** [comment]
@mayurnile another build was released `0.6.1`

**Comment by mayurnile** [comment]
Thank you very much, it works great now on all of the Android Devices and iOS too !
