### ISSUE TITLE
Contact.fromMap causes [ERROR]: `type 'List<dynamic>' is not a subtype of type 'Uint8List'` when avatar is []

### ISSUE THREAD

**Issue by kenaszogara** [lukasgit/flutter_contacts#210]
Step to reproduce:
1.  Create map object using `Contact.toMap()`
2.  Use the returned map object to create an instance of Contact class by using `Contact.fromMap(mapObject)`

```
// get the contacts without thumbnails

List<Contact> contactList = (await ContactsService.getContacts(withThumbnails: false)).toList();

// retrive 1 of the contact
Contact contact = contactList[0];

String jsonData = jsonEconde(contact.toMap());
Contact nContact = new Contact.fromMap(jsonDecode(jsonData)) 
```
on the Contact.fromMap() will return error `type 'List<dynamic>' is not a subtype of type 'Uint8List'`

I fix my issue by adding a try catch block for `this.avatar` inside the Contact.fromMap()
```
// fromMap() code ...
try {
      avatar = m["avatar"];
    } catch (e) {
      avatar = null;
    }
// continuation ...
```

**Comment by ilkerokutman** [comment]
> try {
>       avatar = m["avatar"];
>     } catch (e) {
>       avatar = null;
>     }

Same issue here, fixed by adding same try catch block
