### ISSUE TITLE
unexpected element <queries> found in <manifest>.

### ISSUE THREAD

**Issue by cedvdb** [lukasgit/flutter_contacts#220]
Cannot build app with this dependency.

```
Launching lib\main.dart on Mobile in debug mode...
lib\main.dart:1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     D:\Projects\flutter\sent\build\contacts_service\intermediates\library_manifest\debug\AndroidManifest.xml:11:5-24:15: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin cloud_firestore...
Exception: The plugin cloud_firestore could not be built due to the issue above.
Exited (sigterm)
```

**Comment by Kirpal** [comment]
I fixed this by updating my gradle version.

In `android/build.gradle`:
```gradle
dependencies {
    classpath 'com.android.tools.build:gradle:4.0.1'
    ...
}
```

In `android/gradle/wrapper/gradle-wrapper.properties`:
```
...
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
...
```

**Comment by AhmedAbogameel** [comment]
> I fixed this by updating my gradle version.
> 
> In `android/build.gradle`:
> 
> ```groovy-gradle
> dependencies {
>     classpath 'com.android.tools.build:gradle:4.0.1'
>     ...
> }
> ```
> 
> In `android/gradle/wrapper/gradle-wrapper.properties`:
> 
> ```
> ...
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
> ...
> ```

Super

**Comment by isotopeee** [comment]
> I fixed this by updating my gradle version.
> 
> In `android/build.gradle`:
> 
> ```groovy-gradle
> dependencies {
>     classpath 'com.android.tools.build:gradle:4.0.1'
>     ...
> }
> ```
> 
> In `android/gradle/wrapper/gradle-wrapper.properties`:
> 
> ```
> ...
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
> ...
> ```

It worked for me too! 🙏
