### ISSUE TITLE
Contacts permission is permanently denied on iOS emulator even though permission is granted in settings

### ISSUE THREAD

**Issue by GroovinChip** [lukasgit/flutter_contacts#224]
I've been debugging an issue where contacts don't get loaded on iOS, and I'm seeing that the permission is denied, and then permanently denied when I programmatically request the permission. The trouble is, the option is already granted in the iOS settings app for my application and the prompt does not actually appear.

I'm on the latest version of Flutter on the stable channel, using the latest version of this plugin.

**Comment by araafat3** [comment]
@GroovinChip how you solve it?
