### ISSUE TITLE
Unable to convert Iterable to List - It Throws a Null Exception

### ISSUE THREAD

**Issue by aayushces** [lukasgit/flutter_contacts#227]
ArgumentError (Invalid argument(s) (input): Must not be null) on converting the returned Iterable to a List.

**Comment by mugambi40** [comment]
Any solution for this? Stuck here for two days now.

**Comment by mugambi40** [comment]
It turns out when you uncheck All Exceptions (in visual studio code)  there is no exception thrown and everything works correctly.

![image](https://user-images.githubusercontent.com/16955726/122459745-f3bbc280-cfb9-11eb-8f5e-920f7ac2cf61.png)

**Comment by rmortes** [comment]
Can you provide some code?

**Comment by mugambi40** [comment]
This is the line where exception is experienced: `List<Contact> _contacts = (await ContactsService.getContacts())
         .toList(growable: false);`

**Comment by rmortes** [comment]
Maybe the exception is being handled internally by the plugin? Please, provide where the exception is happening exactly

**Comment by lukasgit** [comment]
See thread in #195
