### ISSUE TITLE
Please update with latest version

### ISSUE THREAD

**Issue by akashlilhare** [lukasgit/flutter_contacts#230]
Showing this error message while I am trying to install the package

`Process finished with exit code 1Because every version of dependencies depends on quiver ^2.0.1 and contacts_service >=0.6.0 depends on quiver ^3.0.0, dependencies is incompatible with contacts_service >=0.6.0.
So, because test_app depends on both contacts_service ^0.6.1 and dependencies any, version solving failed.
pub get failed (1; So, because test_app depends on both contacts_service ^0.6.1 and dependencies any, version solving failed.)
`

**Comment by lukasgit** [comment]
I will look into this issue over the weekend.  Thanks!
