### ISSUE TITLE
NullPointerException issue

### ISSUE THREAD

**Issue by dinesh-utrade** [lukasgit/flutter_contacts#233]
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.CharSequence android.content.res.Resources.getText(int)' on a null object reference
android.provider.ContactsContract$CommonDataKinds$Phone.getTypeLabel (ContactsContract.java:6295)
flutter.plugins.contactsservice.contactsservice.Item.getPhoneLabel (Item.java:4)
flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.getContactsFrom (ContactsServicePlugin.java:213)
flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.access$300 (ContactsServicePlugin.java)
flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground (ContactsServicePlugin.java:92)
flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground (ContactsServicePlugin.java)

**Comment by lukasgit** [comment]
I will look into this issue over the weekend.  Thanks!

**Comment by dinesh-utrade** [comment]
Thanks Lukas

**Comment by faiziatcanz** [comment]
Hi @lukasgit , Any update on this issue?
