### ISSUE TITLE
Contacts stored in SIM card

### ISSUE THREAD

**Issue by mohamoha6200** [lukasgit/flutter_contacts#242]
Hi everyone , this isn't really an issue but I've been looking for a package that supports getting contacts from mobile Sim cards in addition to contacts stored in the phone memory , could you please advise on whether this plugin is able to fetch contacts from Sim cards ?

**Comment by HasanElHefnawy** [comment]
@mohamoha6200 I think this should be an issue. I also couldn't get contacts stored in SIM card.
