### ISSUE TITLE
Module 'contacts_service' not found

### ISSUE THREAD

**Issue by mathan-techjays** [lukasgit/flutter_contacts#245]
#import "GeneratedPluginRegistrant.h"

#if __has_include(<contacts_service/ContactsServicePlugin.h>)
#import <contacts_service/ContactsServicePlugin.h>
#else
@import contacts_service;
#endif

**Comment by canh7antt8a** [comment]
i have same problem

**Comment by Zeeshan0201** [comment]
same issue.

**Comment by Zeeshan0201** [comment]
any update here?

**Comment by Zeeshan0201** [comment]
just recreate new project and paste lib,assets,ios plits files,menifest,ymal and all required file.
then cd ios,pub install,pub update,flutter build ios.
it will work and generate the build.
