### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getContactsForEmail on channel github.com/clovisnicolas/flutter_contacts)

### ISSUE THREAD

**Issue by Dj45chd** [lukasgit/flutter_contacts#247]
Hi Team,

getting below error android device, even though i am using the latest version of the plug(0.6.1) 

pubspec.lock file --> 
dependency: 
  contacts_service:
    dependency: "direct main"
    description:
      name: contacts_service
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.1"

Error --> 
08-16 12:09:18.482 17030 17366 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getContactsForEmail on channel github.com/clovisnicolas/flutter_contacts)
08-16 12:09:18.482 17030 17366 E flutter : #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
08-16 12:09:18.482 17030 17366 E flutter : <asynchronous suspension>
08-16 12:09:18.482 17030 17366 E flutter : #1      ContactsService.getContactsForEmail (package:contacts_service/contacts_service.dart:67)
08-16 12:09:18.482 17030 17366 E flutter : <asynchronous suspension>
08-16 12:09:18.482 17030 17366 E flutter : #2      _AddToContactButtonState._addEmployeeToContact (package:people/widgets/buttons/add_to_contact_button.dart:76)
08-16 12:09:18.482 17030 17366 E flutter : <asynchronous suspension>
08-16 12:09:18.482 17030 17366 E flutter :

**Comment by hadiabdullan** [comment]
I too have the same issue..did you resolved @Dj45chd ??

**Comment by fjbatresv** [comment]
This method is not actually enabled in Android.

**Comment by fjbatresv** [comment]
I've created a fork with support for this: https://github.com/fjbatresv/flutter_contacts

**Comment by lukasgit** [comment]
@fjbatresv thank you for PR #255 
Merged and published build 0.6.3
