### ISSUE TITLE
Error, even when i use example app

### ISSUE THREAD

**Issue by mukhtarfauzi** [lukasgit/flutter_contacts#25]
**Is this plugin still work on a new flutter update?**

[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.295], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code (version 1.38.0)
[√] Connected device (1 available)

**Get this error after getting permission:**

> E/AndroidRuntime(24389): FATAL EXCEPTION: AsyncTask #2
> E/AndroidRuntime(24389): Process: com.indivara.woi_app, PID: 24389
> E/AndroidRuntime(24389): java.lang.RuntimeException: An error occurred while executing doInBackground()
> E/AndroidRuntime(24389): 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
> E/AndroidRuntime(24389): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
> E/AndroidRuntime(24389): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
> E/AndroidRuntime(24389): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
> E/AndroidRuntime(24389): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
> E/AndroidRuntime(24389): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> E/AndroidRuntime(24389): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> E/AndroidRuntime(24389): 	at java.lang.Thread.run(Thread.java:764)
> E/AndroidRuntime(24389): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
> E/AndroidRuntime(24389): 	at flutter.plugins.contactsservice.contactsservice.Contact.compareTo(Contact.java:94)
> E/AndroidRuntime(24389): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask$1.compare(ContactsServicePlugin.java:175)
> E/AndroidRuntime(24389): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask$1.compare(ContactsServicePlugin.java:172)
> E/AndroidRuntime(24389): 	at java.util.TimSort.binarySort(TimSort.java:296)
> E/AndroidRuntime(24389): 	at java.util.TimSort.sort(TimSort.java:239)
> E/AndroidRuntime(24389): 	at java.util.Arrays.sort(Arrays.java:1498)
> E/AndroidRuntime(24389): 	at java.util.ArrayList.sort(ArrayList.java:1470)
> E/AndroidRuntime(24389): 	at java.util.Collections.sort(Collections.java:201)
> E/AndroidRuntime(24389): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:178)
> E/AndroidRuntime(24389): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:137)
> E/AndroidRuntime(24389): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
> E/AndroidRuntime(24389): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> E/AndroidRuntime(24389): 	... 4 more
> I/Process (24389): Sending signal. PID: 24389 SIG: 9
> Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:65522/EItVHkZPrCk=/
> Lost connection to device.

**Comment by LilJaaY** [comment]
I have the same error in my app. The problem was introduced in version 0.3.1.
0.3.0 is working fine.

**Comment by mukhtarfauzi** [comment]
for me, 0.2.9 is working fine.
