### ISSUE TITLE
bad State: No element

### ISSUE THREAD

**Issue by gbbest15** [lukasgit/flutter_contacts#253]
it will fetch some number but when it get to a number it state BAD STATE: NO ELEMENT, which i dont think is from my code

**Comment by zeczen** [comment]
Where are the lines that caused the error?

**Comment by gbbest15** [comment]
is not show error in the code, is just showing BAD STATE: NO ELEMENT

**Comment by VictorUvarov** [comment]
Bad state no element is an error that occurs most commonly when you use the first/last getters on an empty list.

**Comment by gbbest15** [comment]
@VictorUvarov base on the example code, I fellow the example code but I just add only the phone number, like this 
C.phones.first, so i think this is where is see the bad state no element, 

Now 
If I  change it to c.phones.elementAt(0).value will I still get thesame error?
