### ISSUE TITLE
Reopen - Duplicate Numbers #175

### ISSUE THREAD

**Issue by danielnordh** [lukasgit/flutter_contacts#258]
On Android, many contacts return duplicate phone numbers, formatted slightly differently.
It seems to have to do with other apps storing the number again, for example WhatsApp Business storing the same number under 'Video call', 'Voice call' and 'Message'.

It is super annoying and basically not usable in production without filtering.

I suggest the library should:
- Filter and compare each contact's phone numbers
- If duplicates exist, only return ONE instance

Issue #175 was closed by a bot without resolution.

**Comment by rahullogicwind** [comment]
> On Android, many contacts return duplicate phone numbers, formatted slightly differently. It seems to have to do with other apps storing the number again, for example WhatsApp Business storing the same number under 'Video call', 'Voice call' and 'Message'.
> 
> It is super annoying and basically not usable in production without filtering.
> 
> I suggest the library should:
> 
> * Filter and compare each contact's phone numbers
> * If duplicates exist, only return ONE instance
> 
> Issue #175 was closed by a bot without resolution.

Same issue i m currently facing...any solution for that?
