### ISSUE TITLE
error run on version  contacts_service: ^0.6.3

### ISSUE THREAD

**Issue by webelegan** [lukasgit/flutter_contacts#259]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     D:\SRC\Flutter\ppob\build\contacts_service\intermediates\library_manifest\debug\AndroidManifest.xml:11:5-24:15: AAPT: error: unexpected element <queries> found in <manifest>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by eugenioamato** [comment]
I had the same error. Reverted to 0.6.0 it works
Error appearing also on 0.6.1 and 0.6.2
