### ISSUE TITLE
Contacts_Service Must Have SWIFT VERSION

### ISSUE THREAD

**Issue by Kyaw-Zin-Thant** [lukasgit/flutter_contacts#26]
contacts_service does not specify a Swift version when flutter run iOS. How to solve this problem?

**Comment by lukasgit** [comment]
1. Delete the ios folder (you might want to create a backup first)
2. Run this command in the root of the project:  `flutter create -i swift .`

**Comment by fanxiaofan** [comment]
Version is Fixed At Swift4.2, if iOS Project use Swfit5.0 will lead error again
