### ISSUE TITLE
ContactsServicePlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by aleaforny** [lukasgit/flutter_contacts#260]
I'm using `contacts_service` **0.6.3** and am building APK (android).

There is a red note of Flutter:
`C:\Users\f\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\contacts_service-0.6.1\android\src\main\java\flutter\plugins\contactsservice\contactsservice\ContactsServicePlugin.java uses or overrides a deprecated API.`

Is that important? Can you update this API?
Thanks so much.

**Comment by MoaidAlrazhy** [comment]
same here 

you need to look here 
https://docs.flutter.dev/development/packages-and-plugins/plugin-api-migration
