### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by sgarchavada** [lukasgit/flutter_contacts#261]
I have updated this  library to v0.6.3 in my project,
now I am getting this error even If I had this permission already enabled. It was working fine before, now its not.
![photo2](https://user-images.githubusercontent.com/9759741/141610932-78c7354a-8257-46bb-a777-4c75486628aa.png)
![photo2](https://user-images.githubusercontent.com/9759741/141610986-983e4fef-3984-478f-b0ee-c2889b57e474.png)

**Comment by developmentkws** [comment]
Have you solved it ? I am getting same error , I ran Example app and its showing "Contact data not available on device"

**Comment by Eunyeong-Kim** [comment]
Same issue here. Have you soloved it? 
version: contacts_service 0.6.3 
Could you share me the soulution?
