### ISSUE TITLE
Option to use plugin from native

### ISSUE THREAD

**Issue by elihaidv** [lukasgit/flutter_contacts#269]
Hi
I think it will be great if you can open the methods to use them in the native JAVA/Kotlin files, in addition the dart use.
In current, methods like `addContact` are private. So I can't call them from my Native code.

**Comment by elihaidv** [comment]
Hi I forked the repository and made some changes for mine.
You can use it as example to what I mean
https://github.com/elihaidv/flutter_contacts

**Comment by faiziatcanz** [comment]
Hi @elihaidv , Can you please look into to the issue #265 and let me know the problem. Or I will be thankful if you can contribute to it in case you found a solution to it. Its a bit urgent.

Thanks

**Comment by lukasgit** [comment]
Hi there!  This is a community project (my time is very limited, sorry).  Please feel free to contribute your PR for review... thanks!
