### ISSUE TITLE
No contact name error

### ISSUE THREAD

**Issue by wangyy1** [lukasgit/flutter_contacts#27]
@Override
    public int compareTo(Contact contact) {
        return this.givenName.toLowerCase().compareTo(contact.givenName.toLowerCase());
    }

**Comment by wangyy1** [comment]
Add a contact without a name directly to reproduce

**Comment by knyghtryda** [comment]
I think this needs a more broad check of contact info instead of just basing it on name.  Its totally possible to have a valid contact with just a phone number or email, or even just a company name.  The check just needs to be that there's some piece of identifying information to save.
