### ISSUE TITLE
facing issue #250 again on flutter 2.2.3

### ISSUE THREAD

**Issue by jaigahlot** [lukasgit/flutter_contacts#274]
Facing issue described at https://github.com/lukasgit/flutter_contacts/issues/250

Is there any guidance? Will this solution work? https://giters.com/lukasgit/flutter_contacts/issues/250

flutter --version
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (7 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

**Comment by jeromeDms** [comment]
> Facing issue described at #250
> 
> Is there any guidance? Will this solution work? https://giters.com/lukasgit/flutter_contacts/issues/250
> 
> flutter --version Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git Framework • revision f4abaa0735 (7 months ago) • 2021-07-01 12:46:11 -0700 Engine • revision 241c87ad80 Tools • Dart 2.13.4

Hi
Same problem here, did you find a way to solve this ?
Thanks
