### ISSUE TITLE
Module 'contacts_service' not found

### ISSUE THREAD

**Issue by milanobrenovic** [lukasgit/flutter_contacts#275]
this plugin works perfectly fine in development/debug version of the app but whenever i go Runner -> Archive in Xcode (to deploy my app to the app store) the build fails saying 

```Module 'contacts_service' not found```

![image](https://user-images.githubusercontent.com/56999235/151269098-ee621a05-6fc4-4f70-bd9d-82999167ed11.png)

![image](https://user-images.githubusercontent.com/56999235/151269175-6ee3640a-aa89-4267-b387-440c9c832184.png)

what's the problem?

**Comment by fazalullahmemon** [comment]
I am facing this issue as well

**Comment by akshay-appinventiv** [comment]
Facing same issue any updates on this?

**Comment by vmwsree** [comment]
I am facing same issue.

**Comment by vmwsree** [comment]
Setting the deployment target to 12.1 Solves this bug.
