### ISSUE TITLE
In ios unable to check contact permission

### ISSUE THREAD

**Issue by RRohitM** [lukasgit/flutter_contacts#276]
i have use get contact service but unable to get contact list in ios, Showing no contact available on device but contact already available in my device.
i think it's a contact permission issues. I have already define contact permission at run time in our app, 
But permission allow popup could not show how to fix.

**Comment by deep1931** [comment]
Hi, Have you found the solution?
I am facing same issue, I have checked the permission but permission dialog is not opening..

**Comment by lukasgit** [comment]
@deep1931 please follow the guidance @mirkancal provided above
