### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference

### ISSUE THREAD

**Issue by jaigahlot** [lukasgit/flutter_contacts#277]
When you press phone's back button without selecting any contact, the app crashes.
If you use scaffold's back button, it does not crash!

plugin version: 0.6.3

flutter --version
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (8 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

E/AndroidRuntime(31226): FATAL EXCEPTION: main
E/AndroidRuntime(31226): Process: com.golookapp.golook, PID: 31226
E/AndroidRuntime(31226): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=52943, result=1100, data=null} to activity {com.golookapp.golook/com.golookapp.golook.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
E/AndroidRuntime(31226): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5579)
E/AndroidRuntime(31226): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5620)
E/AndroidRuntime(31226): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(31226): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(31226): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(31226): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
E/AndroidRuntime(31226): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31226): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(31226): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
E/AndroidRuntime(31226): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31226): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(31226): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/AndroidRuntime(31226): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
E/AndroidRuntime(31226): 	at e.a.a.a.b$b.a(Unknown Source:27)
E/AndroidRuntime(31226): 	at io.flutter.embedding.engine.c$c.i(Unknown Source:25)
E/AndroidRuntime(31226): 	at io.flutter.embedding.engine.c.a(Unknown Source:15)
E/AndroidRuntime(31226): 	at io.flutter.embedding.android.f.j(Unknown Source:51)
E/AndroidRuntime(31226): 	at io.flutter.embedding.android.e.onActivityResult(Unknown Source:10)
E/AndroidRuntime(31226): 	at android.app.Activity.dispatchActivityResult(Activity.java:8550)
E/AndroidRuntime(31226): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5572)
E/AndroidRuntime(31226): 	... 11 more

**Comment by lukasgit** [comment]
Hi there!  This is a community project (my time is very limited, sorry).  Please feel free to contribute your PR for review... thanks!
