### ISSUE TITLE
iOS contacts not working properly on iPhone 11 physical device

### ISSUE THREAD

**Issue by harnit-bakshi** [lukasgit/flutter_contacts#279]
Hi,
The library works fine for android but when we test iOS the library does not work properly for iOS

Summary:
- iOS Simulator works fine see screenshot (iPhone 11 Pro)
- iOS Physical device not able to display contacts properly (iPhone 11)

See screenshots below, I am using the latest version of the library

**On Physical Device**
![iPhone 11 - Physical Device](https://user-images.githubusercontent.com/53926175/154580443-84e762f9-592d-4926-a36d-ab636e2f4c0c.jpeg)

**On Simulator**
<img width="441" alt="iOS Simulator - Iphone 11 Pro" src="https://user-images.githubusercontent.com/53926175/154580578-06496116-2082-44da-8410-e5c3d58eeac3.png">

Thanks!

**Comment by jmw1493** [comment]
I think I saw this when I first installed this library. I just filtered out the contacts that didn't have a name

**Comment by harnit-bakshi** [comment]
ok I can filter out that, but I also see something strange after I scroll down to more contacts a block of grey, and others also see exactly same patter
![IMG_C647EE8A7F28-1](https://user-images.githubusercontent.com/53926175/154600707-f112e819-7109-475b-a081-1a5261dec0fd.jpeg)

**Comment by harnit-bakshi** [comment]
Sorry my bad all good that was an issue in our code, closing the ticket
