### ISSUE TITLE
Crash when not name contact

### ISSUE THREAD

**Issue by sergio-loro** [lukasgit/flutter_contacts#28]
contact is null the app crash

@Override
public int compareTo(Contact contact) {
    return this.givenName.toLowerCase().compareTo(contact.givenName.toLowerCase());
}

**Comment by sergio-loro** [comment]
off course, when the code substract the android contacs and compare the contact model, sometimes crash because one contact maybe havent display name and this crash the app.

**Comment by sergio-loro** [comment]
off course, when the code substract the android contacs and compare the contact model, sometimes crash because one contact maybe havent display name and this crash the app.

**Comment by edu1525** [comment]
The same issue here, can anybody help-me?

**Comment by lukasgit** [comment]
Merged PR #30 and #31. Updated pub package to 0.3.4
