### ISSUE TITLE
Error: Value must be ≥ 0 [Range]         contactIds.add(phoneCursor.getString(phoneCursor.getColumnIndex(BaseColumns._ID)));

### ISSUE THREAD

**Issue by sultan113054** [lukasgit/flutter_contacts#281]
flutter --version
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (2 months ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

 Task :contacts_service:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':contacts_service:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  The first 3 errors (out of 31) were:
  
  /Users/sultanmahmud/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.6.3/android/src/main/java/flutter/plugins/contactsservice/contactsservice/ContactsServicePlugin.java:534: Error: Value must be ≥ 0 [Range]
        contactIds.add(phoneCursor.getString(phoneCursor.getColumnIndex(BaseColumns._ID)));
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Users/sultanmahmud/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.6.3/android/src/main/java/flutter/plugins/contactsservice/contactsservice/ContactsServicePlugin.java:573: Error: Value must be ≥ 0 [Range]
        String mimeType = cursor.getString(cursor.getColumnIndex(ContactsContract.Data.MIMETYPE));
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Users/sultanmahmud/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.6.3/android/src/main/java/flutter/plugins/contactsservice/contactsservice/ContactsServicePlugin.java:574: Error: Value must be ≥ 0 [Range]
        contact.displayName = cursor.getString(cursor.getColumnIndex(ContactsContract.Contacts.DISPLAY_NAME));

**Comment by lukasgit** [comment]
Hi there!  This is a community project (my time is very limited, sorry).  Please feel free to contribute your PR for review... thanks!
