### ISSUE TITLE
How to open existing contact profile?

### ISSUE THREAD

**Issue by heshaShawky** [lukasgit/flutter_contacts#282]
I'm using the plugin and it's great, I am using the native view to select a contact, now after I select the specific contact I need a way to open it on native view as well! 

I used `await ContactsService.openExistingContact(contact)` but it's opening the contact editing form instead of the profile page which I need.

**Comment by lukasgit** [comment]
Hi there!  This is a community project (my time is very limited, sorry).  Please feel free to contribute your PR for review... thanks!
