### ISSUE TITLE
Reply already submitted

### ISSUE THREAD

**Issue by heshaShawky** [lukasgit/flutter_contacts#283]
The issue is still active on the recent flutter version that is 2.10.2

Plugin version: 
```pubspec
dependencies:
  contacts_service: ^0.6.3
  image_picker: ^0.8.4+10
```

```bash
eshams-MacBook-Pro:masarifi_app esham$ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.2, on macOS 11.4 20F71 darwin-x64, locale en-EG)
    • Flutter version 2.10.2 at /Users/esham/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (11 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/esham/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] VS Code (version 1.33.1)
    • VS Code at /Volumes/Partion-2/Sources/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Redmi Note 8 Pro (mobile) • hev4t4bqo7hyvsnf • android-arm64  • Android 10 (API 29)
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

Issue log:
```bash
D[/AndroidRuntime]()(29357): Shutting down VM
E[/AndroidRuntime]()(29357): FATAL EXCEPTION: main
E[/AndroidRuntime]()(29357): Process: app.masarifi, PID: 29357
E[/AndroidRuntime]()(29357): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2346, result=-1, data=Intent { flg=0x1 clip={image* U:[content://com.android.providers.media.documents/document/image%3A108496]() ...} }} to activity {app.masarifi[/app.masarifi.MainActivity]()}: java.lang.IllegalStateException: Reply already submitted
E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4965)
E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5006)
E[/AndroidRuntime]()(29357): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E[/AndroidRuntime]()(29357): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E[/AndroidRuntime]()(29357): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
E[/AndroidRuntime]()(29357): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E[/AndroidRuntime]()(29357): 	at android.os.Looper.loop(Looper.java:224)
E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.main(ActivityThread.java:7551)
E[/AndroidRuntime]()(29357): 	at java.lang.reflect.Method.invoke(Native Method)
E[/AndroidRuntime]()(29357): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E[/AndroidRuntime]()(29357): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
E[/AndroidRuntime]()(29357): Caused by: java.lang.IllegalStateException: Reply already submitted
E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E[/AndroidRuntime]()(29357): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E[/AndroidRuntime]()(29357): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.finishWithResult(ContactsServicePlugin.java:267)
E[/AndroidRuntime]()(29357): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.onActivityResult(ContactsServicePlugin.java:302)
E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:840)
E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:441)
E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:772)
E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:685)
E[/AndroidRuntime]()(29357): 	at android.app.Activity.dispatchActivityResult(Activity.java:8249)
E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4958)
E[/AndroidRuntime]()(29357): 	... 11 more
I[/Process]() (29357): Sending signal. PID: 29357 SIG: 9
Lost connection to device.
```

**Comment by jeromeDms** [comment]
> The issue is still active on the recent flutter version that is 2.10.2
> 
> Plugin version:
> 
> ```
> dependencies:
>   contacts_service: ^0.6.3
>   image_picker: ^0.8.4+10
> ```
> 
>  ```shell
> eshams-MacBook-Pro:masarifi_app esham$ flutter doctor -v
> [✓] Flutter (Channel stable, 2.10.2, on macOS 11.4 20F71 darwin-x64, locale en-EG)
>     • Flutter version 2.10.2 at /Users/esham/Development/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 097d3313d8 (11 days ago), 2022-02-18 19:33:08 -0600
>     • Engine revision a83ed0e5e3
>     • Dart version 2.16.1
>     • DevTools version 2.9.2
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/esham/Library/Android/sdk
>     ✗ cmdline-tools component is missing
>       Run `path/to/sdkmanager --install "cmdline-tools;latest"`
>       See https://developer.android.com/studio/command-line for more details.
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.0)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
> 
> [✓] VS Code (version 1.64.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.34.0
> 
> [✓] VS Code (version 1.33.1)
>     • VS Code at /Volumes/Partion-2/Sources/Visual Studio Code.app/Contents
>     • Flutter extension version 3.34.0
> 
> [✓] Connected device (2 available)
>     • Redmi Note 8 Pro (mobile) • hev4t4bqo7hyvsnf • android-arm64  • Android 10 (API 29)
>     • Chrome (web)              • chrome           • web-javascript • Google Chrome 98.0.4758.109
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> ! Doctor found issues in 1 category.
> ```
> 
> Issue log:
> 
> ```shell
> D[/AndroidRuntime]()(29357): Shutting down VM
> E[/AndroidRuntime]()(29357): FATAL EXCEPTION: main
> E[/AndroidRuntime]()(29357): Process: app.masarifi, PID: 29357
> E[/AndroidRuntime]()(29357): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2346, result=-1, data=Intent { flg=0x1 clip={image* U:[content://com.android.providers.media.documents/document/image%3A108496]() ...} }} to activity {app.masarifi[/app.masarifi.MainActivity]()}: java.lang.IllegalStateException: Reply already submitted
> E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4965)
> E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5006)
> E[/AndroidRuntime]()(29357): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
> E[/AndroidRuntime]()(29357): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> E[/AndroidRuntime]()(29357): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
> E[/AndroidRuntime]()(29357): 	at android.os.Handler.dispatchMessage(Handler.java:107)
> E[/AndroidRuntime]()(29357): 	at android.os.Looper.loop(Looper.java:224)
> E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.main(ActivityThread.java:7551)
> E[/AndroidRuntime]()(29357): 	at java.lang.reflect.Method.invoke(Native Method)
> E[/AndroidRuntime]()(29357): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
> E[/AndroidRuntime]()(29357): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
> E[/AndroidRuntime]()(29357): Caused by: java.lang.IllegalStateException: Reply already submitted
> E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
> E[/AndroidRuntime]()(29357): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
> E[/AndroidRuntime]()(29357): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.finishWithResult(ContactsServicePlugin.java:267)
> E[/AndroidRuntime]()(29357): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.onActivityResult(ContactsServicePlugin.java:302)
> E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:840)
> E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:441)
> E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:772)
> E[/AndroidRuntime]()(29357): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:685)
> E[/AndroidRuntime]()(29357): 	at android.app.Activity.dispatchActivityResult(Activity.java:8249)
> E[/AndroidRuntime]()(29357): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4958)
> E[/AndroidRuntime]()(29357): 	... 11 more
> I[/Process]() (29357): Sending signal. PID: 29357 SIG: 9
> Lost connection to device.
> ```

Hi
I'm facing the same issue, did you find a way to fix this ?
Thanks
