### ISSUE TITLE
Update contact and delete contact not working

### ISSUE THREAD

**Issue by logispire** [lukasgit/flutter_contacts#306]
### Update contact not working properly
**I am getting bizarre issues while updating the contact, I am not getting any errors but my mobile number is getting removed when I update it.**
my code is like this 
```
Contact? duplicateContact = <old contact>;

duplicateContact.givenName = "new name";
duplicateContact.company = "new company name";
duplicateContact.phones = [
      Item(value: "9876738211", label: "mobile")
];

await ContactsService.updateContact(duplicateContact);
```

so in contact data - **the mobile number is getting removed** even if I specified the mobile number in the newly updated object.

### Delete contact not working

when I am trying to delete the contact, I am getting an error message from the application system

![IMG_20230105_200843](https://user-images.githubusercontent.com/87352568/210805716-98cbe726-fe4c-426b-829d-cf80cbab0bbd.jpg)

**so overall I am not able to update or delete contact service**
i am stuck into this for last 10 to 15 days, so anyone can help, it will be appreciated

**Comment by codetinker** [comment]
I had the similar problem. 

    List<Contact> contacts = await ContactsService.getContacts(
      withThumbnails: false,
      photoHighResolution: false,
      orderByGivenName: false,
    );
    
    for (Contact c in contacts) {
        String formatted = c.phones![0].value.toString().replaceAll('-', '').replaceAll('#', '').replaceAll('*', '').replaceAll(' ', '').replaceAll('+', '').replaceAll('(', '').replaceAll(')', '').replaceAll('#', '');
        if (formatted == phone) {
            Item nPhone = Item(label: 'mobile', value: phone);
            Contact newContact = Contact(identifier: c.identifier, phones: [nPhone], givenName: fname, familyName: lname, displayName: '$fname $lname');
            await ContactsService.updateContact(newContact);
        }
    }

Intead of update, it delete the contact =(
Please advice

**Comment by codetinker** [comment]
Im using this code to update

    // Create first the update.. instead of update then create. There is different
    Contact newContact = Contact(phones: [nPhone], givenName: fname, familyName: lname, displayName: '$fname $lname');
    await ContactsService.addContact(newContact);

    Contact updateContact = Contact(identifier: c.identifier, phones: [nPhone], givenName: fname, familyName: lname, displayName: '$fname $lname');
    await ContactsService.updateContact(updateContact);
    
    
and this code alone to delete ^^

    Contact updateContact = Contact(identifier: c.identifier, phones: [nPhone], givenName: fname, familyName: lname, displayName: '$fname $lname');
    await ContactsService.updateContact(updateContact);

**Comment by logispire** [comment]
@codetinker i noticed that you are getting a similar issue, can you please tell me if you found any solution regarding this, i am getting another issue is like -
when I am adding contacts to my phone in the loop [save multiple contacts] - one person's mobile number is combined with another person's mobile number [very weird], I tried to find out solution, but not got any solution yet.

**Comment by codetinker** [comment]
@logispire same problem here. Most my contacts messed up. Luckily i did backup first. 
It was working with single contact. But when saving multiple contacts, the contacts got overwritten very weird. Some contact mixed with multiple phone numbers. Most got messed up very bad. The contacts does not even belong to the number. Very weird. 

I thinking trying other package available. Else maybe need find and fix at the source code.
So I have no solution yet.

**Comment by logispire** [comment]
@codetinker thanks for sharing the issue that you are also facing, i tried another packages like [flutter_contacts] (https://pub.dev/packages/flutter_contacts) , but here when i update the app in play store, play store is rejecting my app for violating privacy policy i tried to fix it but nothing works
play store gives me an error as -
**APK HAS A PRIVACY POLICY​ BUT IT IS NOT ADEQUATE
Your app is uploading users' Contact List & Images information without posting a privacy policy in Play Distributed App.**

**Comment by codetinker** [comment]
@logispire urwc. I saw package flutter_contacts before, but haven't try it yet. How did it go? Work well?

For playstore error, I think you need to update the policy in playstore. There is questionnaire, I remember before publishing the app. There so many questions asking how I manage the data. Including name, phone, email etc. You need to answer this correctly. 

Check under left menu bar > Policy and programs > App content > Data safety
I think that's the one causing the error. Else check all the policies there

**Comment by logispire** [comment]
@codetinker thanks for the quick reply, when I used`flutter_contacts` and make an update in the play store, I already verify the play console data safety questionnaire and checked true the contact permission, I also display a dialog to users that the contract will be managed in this app, but still play console is rejecting my submission,
I think i have to go with the `flutter_contacts` plugin, but..add and update contact not working properly

**Comment by lukasgit** [comment]
#309
