### ISSUE TITLE
LOOKING FOR CONTRIBUTORS

### ISSUE THREAD

**Issue by lukasgit** [lukasgit/flutter_contacts#309]
Hello everyone,

Looking for two or more contributors to help with maintaining the popular Flutter [contacts_service](https://pub.dev/packages/contacts_service) package:

- Responding to Issues
- Managing Pull requests

There is a lot of demand for this package, and developers need this package maintained.  Your contribution will be appreciated by many folks.

Please reply directly to this thread if you are able to contribute.  Thanks!

**Comment by MahendraN35** [comment]
Hi @lukasgit. I'd like to contribute to maintain this package.

**Comment by usamamanzoor07** [comment]
Hi @lukasgit. I would love to contribute to or maintain this wonderful package. I can share your burden on responding to issues and managing Pull Requests.

**Comment by logispire** [comment]
> Hi @lukasgit. I'd like to contribute to maintain this package.

what is your contribution to solving these issues? can you please share or provide more details regarding that, this plugin is useless for saving multiple contacts.

here is my issue [https://github.com/lukasgit/flutter_contacts/issues/306](Issue)

**Comment by lukasgit** [comment]
Looking for qualified contributors to help maintain this package.

**Comment by makwasi1** [comment]
I would like to help contribute to this package.

**Comment by nvanderwaal** [comment]
Hi @lukasgit,
We utilize this package and would like to offer assistance where necessary. Do you still need contributers?

**Comment by nickf2k** [comment]
Hello @lukasgit! I'm a Flutter developer with approximately 5 years of experience. I've worked on several projects and am familiar with Git workflows. Is there a way for me to contribute to this project?
