### ISSUE TITLE
Contact saved with wrong label

### ISSUE THREAD

**Issue by skibos** [lukasgit/flutter_contacts#311]
Hi. 

```
          final newContact = Contact();
            newContact.phones = [Item(label: "mobile", value:"+48xxxxxxxxx")];
          await ContactsService.addContact(newContact);
```

When I run this code (x - are numbers) it will add contact but with "Custom" label not mobile. What is strange - when I will use editExistingContact its filled with "Mobile" but when you add and go to contact list you will see custom, so if you will edit and click "Save" it will be mobile, otherwise it will be Custom.

Tested on Android 11

**Comment by gbfarah** [comment]
Im reopening this... Is this library maintained ?
Trying to add a new contact is not adhering to the phone types

**Comment by nvanderwaal** [comment]
Contact.phones is a `List<Phone>?` which means that a better approach is to use the actual `Phone` class with its `PhoneLabel` enum
```
final newContact = Contact()
  ..phones = [Phone("+48xxxxxxxxx", label:  PhoneLabel.mobile)]
```

If you'd like to add a custom label you can do the following with using the `phoneLabel.custom` enum
```
final newContact = Contact()
  ..phones = [Phone("+48xxxxxxxxx", label:  PhoneLabel.custom, customLabel: 'My custom label')]
```
