### ISSUE TITLE
OpenContactForm should take initial Contact

### ISSUE THREAD

**Issue by Muhammadjaved7209** [lukasgit/flutter_contacts#315]
Contact newContact = new Contact();

                  newContact.givenName = "Ajay";
                  newContact.familyName = "abc";

                  newContact.phones = [
                    Item(label: "mobile", value: "9998887771")
                  ];
 ContactsService.openContactForm(
                    
                       
                      androidLocalizedLabels: true, iOSLocalizedLabels: true);

using openContactForm the native save contact form is open...
but it does not take initial contact as a parameter so that the fields must be prefilled when form is open...

**Comment by onursahindur** [comment]
+1

**Comment by kingkarki** [comment]
@Muhammadjaved7209 i have same problem how you fixed this issue ?
