### ISSUE TITLE
ios contacts

### ISSUE THREAD

**Issue by abdullah-onus** [lukasgit/flutter_contacts#316]
in ios does not came guides. also we cant see contact permissin in phone settings

**Comment by jhonaustin412** [comment]
As a user, it seems that there are two issues you're experiencing with iOS. Firstly, you mentioned that there are no guides available. It's unfortunate that you're unable to access the guides you need, as they can be helpful for navigating and understanding the [iOS Robotic](https://www.appsgenii.us/) system. Secondly, you mentioned that you're unable to see the contact permission in the phone settings. This could indicate a potential issue with the iOS settings or a specific app that requires contact access. It may be worth reaching out to Apple support or checking for any available software updates to address these concerns.
