### ISSUE TITLE
Sometimes it works and sometimes doesn't

### ISSUE THREAD

**Issue by Coinizy1** [lukasgit/flutter_contacts#32]
Hi everyone. Anyone facing the same issue? i am trying to get my phone's contacts but the issue is, it only works (90% of the times) on my device and sometimes it works on other devices why is that?
i have also added permissions but still same issue.
https://stackoverflow.com/questions/57921348/fetching-contacts-in-flutter

**Comment by ismadev** [comment]
Same here! :( 
At the beginning, in my testing phone 1, I was facing the same issue. But **I cleaned some contacts that are not linked to a phone number** and this package started working!

But in my testing phone 2, I'm having the same error, I havent cleaned the contacts yet.

I am using this permission handler package "permission_handler".
The permissions are correct (thats why in phone 1, the "flutter_contacts" package works perfectly).
<uses-permission android:name="android.permission.INTERNET"></uses-permission>
<uses-permission android:name="android.permission.READ_CONTACTS"></uses-permission>
<uses-permission android:name="android.permission.WRITE_CONTACTS"></uses-permission>

This is the line where I get the contacts:
Iterable<Contact> _phoneContactList = await ContactsService.getContacts(withThumbnails: false);

This is the error:
E/AndroidRuntime( 2679): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask$1.compare(ContactsServicePlugin.java:172)
E/AndroidRuntime( 2679): 	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:325)
E/AndroidRuntime( 2679): 	at java.util.TimSort.sort(TimSort.java:199)
E/AndroidRuntime( 2679): 	at java.util.Arrays.sort(Arrays.java:1998)
E/AndroidRuntime( 2679): 	at java.util.Collections.sort(Collections.java:1900)
E/AndroidRuntime( 2679): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:178)
E/AndroidRuntime( 2679): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:137)
E/AndroidRuntime( 2679): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
E/AndroidRuntime( 2679): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 2679): 	... 4 more
W/art     ( 2679): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[20,tid=2752,Native,Thread*=0x80b05088,peer=0x130a00a0,"Thread-21364"]
I/Process ( 2679): Sending signal. PID: 2679 SIG: 9
Lost connection to device.

**Comment by ismadev** [comment]
I have just notice, this is the same issue than #28 
This PR #30 will solve it.

**Comment by thiyagab** [comment]
This issue always keeps coming for me, I approved the PR raised.  Can @lukasgit please review and approve this changes.   Seems like its breaking after latest flutter upgrade.

**Comment by lukasgit** [comment]
Merged PR #30 and #31. Updated pub package to 0.3.4
