### ISSUE TITLE
ERROR: Cannot find header file on ios build

### ISSUE THREAD

**Issue by AJearyzhe** [lukasgit/flutter_contacts#34]
error: /Users/Home/SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.3.3/ios/Classes/ContactsServicePlugin.h: No such file or directory

Also to note this path does not exist after Home".

The path on my pc is /Users/Home/dev/SDKs/

I changed the path of my flutter sdk and the problem cleared. But thats not ideal. All other plugins were ok apart from this one.

**Comment by lukasgit** [comment]
@AJearyzhe did you try running `flutter clean` to clear out the cache?

**Comment by AJearyzhe** [comment]
@lukasgit  Yes, I tried that. I did not work. Somehow the path to the flutter SDK was wrong, and this was the only package causing the error.

**Comment by lukasgit** [comment]
@AJearyzhe did you find a resolution?

**Comment by lukasgit** [comment]
I'm closing this issue as others are not reporting similar problems. If you believe this is not an isolated issue, please feel free to re-open this issue. Thanks! Lukas
