### ISSUE TITLE
Load account identifier as part of Contact

### ISSUE THREAD

**Issue by megid2** [lukasgit/flutter_contacts#35]
At least on Android, each Contact is linked to an account (e.g. Google, Exchange or DAV). Currently it is neither visible e.g. as a field in Contact, much less updateable.

From previous Android experience, I know it is a pain in the ass -- it is not possible to just change the account, you'd have to delete the contact from one account and add it to the next. Still, being able to choose the account at least at creation is important, e.g. to sync the contact to the right Google/Exchange/davx account.

**Comment by 926** [comment]
@megid2 maybe we could split this issues into two parts and start by being able to select from which account contacts are pulled.

**Comment by megid2** [comment]
Ok 926, agreed; changed the title to reflect the issue split. So this issue is an enhancement wish, namely that the account id is loaded as part of the contact.

**Comment by megid2** [comment]
Follow-up is #41

**Comment by 926** [comment]
Thanks for the quick reply,
Might use this repo as a starting point : 
https://github.com/BaseflowIT/flutter-contacts-plugin
It provides an easy access to the platform specific address book
