### ISSUE TITLE
Does add_contact return a status or exception?

### ISSUE THREAD

**Issue by JERINJACOBCHERIAN** [lukasgit/flutter_contacts#36]
newContact.displayName="Jerin";
    newContact.phones = []..add(Item.fromMap({'label': 'work', 'value': phoneNumber})); // Set the label of your choice
    // Add a contact
    // The contact must have a firstName / lastName to be successfully added
    await ContactsService.addContact(newContact);

I have done this, it executes but contact is not added. Is it because I havent added the first name and last? But I have given display name. Model doesnt have definition for first and last name?

So does the function return a status?

**Comment by athilams** [comment]
I'm having the same issue. It is a good idea to return whether the contact was or was not added to user contacts.

**Comment by lukasgit** [comment]
Please feel free to contribute your PR, thanks!
