### ISSUE TITLE
Delay while loading contacts

### ISSUE THREAD

**Issue by tonini46** [lukasgit/flutter_contacts#4]
I am having a problem loading my contact list of about 2113 contacts, It is taking the plugin example app a whole 10 min to display my contacts. I just want to know whether there is a work around for accessing my contacts directly from my phonebook.

**Comment by lukasgit** [comment]
@tonini46 I am not the original author of this plugin. The current plugin has its limitations, and the issue you are experiencing might be related to the limitations.  We are working on re-writing this plugin from the ground up that is clean, secure, flexible, and easy to maintain.

**Comment by lukasgit** [comment]
@tonini46 if you find a resolution to this issue or a workaround, I encourage you to share it here with the community. Thanks

**Comment by aloisdeniel** [comment]
Maybe adding pagination would be useful ?

Something like the following:

```
final total = await ContactsService.contactCount();
for(int i = 0; i < total, i+=40) {
    final total = await ContactsService.getContacts(offset: i, limit: 40);
}
```

Having a method that only querie phone numbers for example would allow to cache data and query only phones that aren't cached ?

```
final allPhones = await ContactsService.getPhones();
final missingPhonesFromCache = MyPhoneCache.phoneNumbers.where((p) => !allPhones .contains(p));
final newContacts = await ContactsService.getContacts(phones: missingPhonesFromCache);
```
