### ISSUE TITLE
Deleting contacts with same name

### ISSUE THREAD

**Issue by danijelzolic1** [lukasgit/flutter_contacts#40]
Hi,

First of all, great plugin. Makes life easy.

My problem, on a One Plus running Android 9, is that if I have a contact ("John") that was created through the phone, I then create (ContactsService.addContact) a contact through the app with the exact same name ("John"), which results in a combined contact between these two. This is not so much of an issue and is probably just how the phone works. The issue is when I want to delete (ContactsService.deleteContact) the app-created contact through the app, it also deletes the old phone-created contact.

Not sure if the case is the on iOS.

So my question is, is there any solution to this?

I assume this is related to:
[http://android-contact-id-vs-raw-contact-id.blogspot.com/](url)

**Comment by lukasgit** [comment]
@danijelzolic1 thanks for the comment and question. Unfortunately, as you pointed out, it's related to the phone. There are hacks to differentiating contacts created with your app.
