### ISSUE TITLE
Enable updating the account of a Contact

### ISSUE THREAD

**Issue by megid2** [lukasgit/flutter_contacts#41]
Followup from #35 which was concerned with adding account identifier to contact.

This issue is an enhancement wish, namely being able to change the account identifier in a loaded or new contact, then updating it.

**Comment by JoseVargas05** [comment]
I have seen that the pattern of contacts that cannot be modified have a link to the icloud or to another platform, for this reason it is impossible to modify it .. A contact normally stored in the cell phone if it can be modified. Is there a way to detect if the contact is synchronized or saved normally?
