### ISSUE TITLE
Allow lazy loading of avatars

### ISSUE THREAD

**Issue by mehmetf** [lukasgit/flutter_contacts#43]
Avatars are currently loaded eagerly from the contact service. We should give the option to lazy load them.

**Comment by knyghtryda** [comment]
+1, but really, all contact info need to be lazy loaded from a stream, not a future.

**Comment by mehmetf** [comment]
This is not about Dart API. It is also about the native implementation. Lazy loading should be done on the native side (i.e. don't request avatars from contact API until the Dart application actually requests it).

It would not be beneficial to do this for other contact info.

**Comment by RafaRuiz** [comment]
Wondering, why is this only done for Android?
