### ISSUE TITLE
Add instrumented unit test to Android part.

### ISSUE THREAD

**Issue by megid2** [lukasgit/flutter_contacts#52]
I tried adding an instrumented unit test to the Android part but found myself quickly in gradle dependency hell. If it is easy for you, could you add one?

This would make contributing much easier. I have started an Android only project to work on the accounts, but are unable to test the stuff on the contacts_service Android part atm.

**Comment by megid2** [comment]
In particular, I struggle to understand why in the I cant add androidx.* to the contacts_service module within the android part.

**Comment by megid2** [comment]
Ok, I have given up on flutter contacts_service for the moment and have copied the Java classes to my own Android project. If I get something done, I will provide it for you.

**Comment by lukasgit** [comment]
@megid2 we welcome the community to contribute to this project by submitting PR's. Thanks!
