### ISSUE TITLE
Can't get avatar of contact

### ISSUE THREAD

**Issue by huuhieupham189** [lukasgit/flutter_contacts#62]
I get contact infor successfully but have a exception. Then the avatar only show text.
  
`Unhandled Exception: MissingPluginException(No implementation found for method getAvatar on channel github.com/clovisnicolas/flutter_contacts)`

**Comment by lukasgit** [comment]
@huuhieupham189 github.com/clovisnicolas/flutter_contacts is an old branch.

Please use https://github.com/lukasgit/flutter_contacts and the latest plugin at https://pub.dev/packages/contacts_service
