### ISSUE TITLE
Error on ContactsService.getContacts()

### ISSUE THREAD

**Issue by Funnyman420** [lukasgit/flutter_contacts#71]
When i try to get the contacts, while they do arrive when the future ends, the single property of the iterable contains an exception, which includes this message.

"BadState: Too many elements".

The interesting thing is that if i don't use it in a widget it still throws that error. But if disable the uncaught and all exceptions of  vscode then it manages to return the Iterable just fine.

![image](https://user-images.githubusercontent.com/38563912/72768711-f9fd1200-3c00-11ea-8b48-8472ba697f88.png)

**Comment by ZmanElete** [comment]
I am having this issue aswell. Any Ideas on how to fix it?

**Comment by mayank99** [comment]
This is definitely still an issue.

**Comment by lukasgit** [comment]
@Funnyman420 @ZmanElete @mayank99 the plugin has recently been updated. Please try again using the latest version 0.4.2

**Comment by mayank99** [comment]
Just tried it on 0.4.2 (I was running 0.4.1 during my original comment). Same error when calling `ContactsService.getContacts`.

> ArgumentError (Invalid argument(s) (input): Must not be null)

**Comment by Funnyman420** [comment]
And if you make another project with the same code, it will work just fine. I don't think that this is some issue with the plugin. It has more likely to do with dart itself. But, unfortunately they closed my issue because they think that the plugin has the bug.

**Comment by lukasgit** [comment]
@mayank99 can you confirm what @Funnyman420 said, that if when you make another project with the same code it works?

**Comment by mayank99** [comment]
I got the same exception on a different project.

One thing to note is that the exception only shows up when the "All Exceptions" box is checked. And if you uncheck that box, the app works [seemingly] fine. So I also do believe the problem has to do with dart/flutter not this plugin.
![image](https://user-images.githubusercontent.com/9084735/80026620-0ca91080-84a8-11ea-8aad-3724e17adead.png)

**Comment by lukasgit** [comment]
@mayank99 @Funnyman420 please file a new issue with Dart team [here](https://github.com/dart-lang/sdk/issues) and Flutter team [here](https://github.com/flutter/flutter/issues)
