### ISSUE TITLE
call to getContacts() crashes Android emulator without stacktrace

### ISSUE THREAD

**Issue by rylem33** [lukasgit/flutter_contacts#72]
I'm attempting to incorporate Contacts Service into my Flutter app.  I have configured my manifest to include read and write permissions on contacts.  I have verified the app requests and confirms permissions correctly for read/write on contacts.  When attempting to call getContacts() from within my app-flow, the app immediately exits with no debug or stacktrace.  Thinking I may have called something in an odd order, I removed my app-flow and copy/pasted the example widget into my app.   On call, the app immediately exits with no debug or stacktrace.

Here is the output on my Android SDK run console:
I/flutter (19587): Get contacts
Lost connection to device.

Here are my manifest statements:
![image](https://user-images.githubusercontent.com/60189193/72911163-9c072200-3d07-11ea-9418-9b83b4451e0f.png)

Here is my original call to getContacts():

    Future<void> _getFriendList() async {
        Iterable<Contact> contacts;

        PermissionStatus permissionStatus = await _getPermission();

        if (permissionStatus == PermissionStatus.granted) {
            debugPrint("Get contacts");

            var contacts = await ContactsService.getContacts(withThumbnails: false);
            debugPrint("test");

            if (contacts != null) {
                contacts.forEach((contact) {
                    debugPrint("contact");
                    //addFriendToList(contact.displayName);
                });
            }
        }
        else {
            debugPrint("_getFriendList:  Could not get permission.");
        }
    }

    Future<PermissionStatus> _getPermission() async {

        PermissionStatus permission = await PermissionHandler().checkPermissionStatus(PermissionGroup.contacts);

        if (permission != PermissionStatus.granted && permission != PermissionStatus.disabled) {
            Map<PermissionGroup, PermissionStatus> permisionStatus = await PermissionHandler().requestPermissions([PermissionGroup.contacts]);
            debugPrint("permisionStatus " + permisionStatus.toString());
            return permisionStatus[PermissionGroup.contacts] ?? PermissionStatus.unknown;
        }
        else {
            return permission;
        }
    }

Here is my Flutter Doctor output:
D:\Applications\flutter\flutter_windows_v1.5.4-hotfix.2-stable\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.592], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at D:\Applications\flutter\flutter_windows_v1.5.4-hotfix.2-stable\flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Marc\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Marc\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = D:\Applications\Android SDK
    • Java binary at: D:\Applications\Android SDK\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Applications\Android SDK
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
Process finished with exit code 0

**Edit:  I confirmed the same behavior exists on my Samsung S7 hardware.**

**Comment by erperejildo** [comment]
Same for me on emulator and Xiaomi Note 8T
