### ISSUE TITLE
Error when trying update contacts

### ISSUE THREAD

**Issue by HugoLimon** [lukasgit/flutter_contacts#8]
When i'm trying update a contact, it doesnt save phones.
i'm using the example code. I'm thinking that the problem was in contact maping but i didn't find the error.

here is my update code 
`
class UpdateContactsPage extends StatefulWidget {
  UpdateContactsPage({ @required this.contact });
  final Contact contact;
  @override
  _UpdateContactsPageState createState() => _UpdateContactsPageState();
}

class _UpdateContactsPageState extends State<UpdateContactsPage> {
  Contact contact;
  PostalAddress address = PostalAddress(label: "Home");
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  @override
  void initState() {
    super.initState();
    contact = widget.contact;
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Update Contact"),
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.save, color: Colors.white,),
            onPressed: () async {
              _formKey.currentState.save();
              contact.postalAddresses = [address];
              await ContactsService.updateContact(contact);
              Navigator.of(context).pop();
            },
          ),
        ],
      ),
      body: Container(
        padding: EdgeInsets.all(12.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: <Widget>[
              TextFormField(
                initialValue: contact.givenName ?? "",
                decoration: const InputDecoration(labelText: 'First name'),
                onSaved: (v) => contact.givenName = v,
              ),
              TextFormField(
                initialValue: contact.middleName ?? "",
                decoration: const InputDecoration(labelText: 'Middle name'),
                onSaved: (v) => contact.middleName = v,
              ),
              TextFormField(
                initialValue: contact.familyName ?? "",
                decoration: const InputDecoration(labelText: 'Last name'),
                onSaved: (v) => contact.familyName = v,
              ),
              TextFormField(
                initialValue: contact.prefix ?? "",
                decoration: const InputDecoration(labelText: 'Prefix'),
                onSaved: (v) => contact.prefix = v,
              ),
              TextFormField(
                initialValue: contact.suffix ?? "",
                decoration: const InputDecoration(labelText: 'Suffix'),
                onSaved: (v) => contact.suffix = v,
              ),
              TextFormField(
                decoration: const InputDecoration(labelText: 'Phone'),
                onSaved: (v) => contact.phones = [Item(label: "mobile", value: v)],
                keyboardType: TextInputType.phone,
              ),
              TextFormField(
                decoration: const InputDecoration(labelText: 'E-mail'),
                onSaved: (v) => contact.emails = [Item(label: "work", value: v)],
                keyboardType: TextInputType.emailAddress,
              ),
              TextFormField(
                initialValue: contact.company ?? "",
                decoration: const InputDecoration(labelText: 'Company'),
                onSaved: (v) => contact.company = v,
              ),
              TextFormField(
                initialValue: contact.jobTitle ?? "",
                decoration: const InputDecoration(labelText: 'Job'),
                onSaved: (v) => contact.jobTitle = v,
              ),
              TextFormField(
                initialValue: contact.note ?? "",
                decoration: const InputDecoration(labelText: 'Note'),
                onSaved: (v) => contact.note = v,
              ),
              TextFormField(
                initialValue: address.street ?? "",
                decoration: const InputDecoration(labelText: 'Street'),
                onSaved: (v) => address.street = v,
              ),
              TextFormField(
                initialValue: address.city ?? "",
                decoration: const InputDecoration(labelText: 'City'),
                onSaved: (v) => address.city = v,
              ),
              TextFormField(
                initialValue: address.region ?? "",
                decoration: const InputDecoration(labelText: 'Region'),
                onSaved: (v) => address.region = v,
              ),
              TextFormField(
                initialValue: address.postcode ?? "",
                decoration: const InputDecoration(labelText: 'Postal code'),
                onSaved: (v) => address.postcode = v,
              ),
              TextFormField(
                initialValue: address.country ?? "",
                decoration: const InputDecoration(labelText: 'Country'),
                onSaved: (v) => address.country = v,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
`

**Comment by HugoLimon** [comment]
it works find when i add a new contact and delete

**Comment by thuraucsy** [comment]
Me too. any work around for the ContactsService.updateContact()?

**Comment by lukasgit** [comment]
@HugoLimon @thuraucsy heads up, I am not the original author of this plugin. This plugin was written early on and has its limitations. The issue you are experiencing might be related to the limitations. We are working on re-writing a new plugin to replace this plugin from the ground up that is clean, secure, flexible, and easy to maintain.

Our resources are limited, but please feel free to contribute to the current plugin with your fixes / improvements. Please see the README for more information on how to contribute. Thanks!

**Comment by thuraucsy** [comment]
I'm sorry for the misinformation. 
I just updating the Contact.displayName and wanted the Android Contact App Name updating. 

In fact, the Android Contact App is using Contact.givenName.

**Comment by arturo-ojeda** [comment]
I tried searching for the error here too but found nothing.

Tried a couple of workarounds on how to compose the new phones object under Flutter but I still get a weird behavior.

It works for some contacts on the device and it seems to work on the emulator but it's flaky, I haven't been able to attribute the cause to one thing.

**Comment by joachimvalente** [comment]
The error is in
https://github.com/lukasgit/flutter_contacts/blob/88905dda5836efcf128e8b6470792776efe414fb/android/src/main/java/flutter/plugins/contactsservice/contactsservice/ContactsServicePlugin.java#L575

Namely we should be looking up by RAW_CONTACT_ID and not by CONTACT_ID, and `contact.identifier` is the CONTACT_ID.

This should fix it: https://github.com/fluttercommunity/flutter_contacts/compare/52b9336...bb00de4

**Comment by ajaysr047** [comment]
Hi everyone, I am new to flutter and I am facing trouble adding new contact using the plugin. Can anyone help me out with an example snippet for adding contact in flutter.
