### ISSUE TITLE
Add Note field to contact

### ISSUE THREAD

**Issue by mohammadne** [lukasgit/flutter_contacts#80]
in my case I need to add a note for every contact i will be add .
I searched and see in 2 phones that there is a field for notes.
it is appreciated to add it into Contact.
Thanks.

**Comment by prajwalmr62** [comment]
It was there in 0.2.9, but was removed in 0.3.x I have no clue why.

**Comment by lukasgit** [comment]
Hi @mohammadne Apple iOS 13 removed notes for privacy reasons.

https://github.com/lukasgit/flutter_contacts/issues/2#issuecomment-540896905
