### ISSUE TITLE
How to get value of contact number??

### ISSUE THREAD

**Issue by urvashikharecha** [lukasgit/flutter_contacts#81]
I am new to flutter ..
i want display contact list with name and number .... from your example i can able to display name but i dont know how can i show number as well..?

please help
thanks in advance !!

**Comment by lpdyck** [comment]
If you just wanted to print them out, you could try something like this:
```
final contacts = await ContactsService.getContacts();
_contacts.forEach(
  (contact) {
    print(contact.displayName);
    contact.phones
        .forEach((phone) => print('${phone.label}: ${phone.value}'));

    contact.emails
        .forEach((email) => print('${email.label}: ${email.value}'));
  },
);
```
Hopefully you can extrapolate from there 🙂
