### ISSUE TITLE
problem with xcode build

### ISSUE THREAD

**Issue by mdnurfikriabdghani** [lukasgit/flutter_contacts#83]
got error when build using xcode
 >> Module 'contacts_service' not found

╰─➤  flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
[✓] VS Code (version 1.43.1)
[✓] Connected device (2 available)
<img width="1135" alt="Screenshot 2020-03-29 at 6 56 59 PM" src="https://user-images.githubusercontent.com/59432641/77847418-80306880-71ef-11ea-8bd3-d08e07969e26.png">

**Comment by lukasgit** [comment]
@mdnurfikriabdghani are you able to build and run the flutter example app?

**Comment by lukasgit** [comment]
@mdnurfikriabdghani this plugin has been updated. Please try again using the latest version 0.4.2 released today.

**Comment by simon-twonary** [comment]
@lukasgit  Got this error when compiling on Xcode

# SwiftContactsServicePlugin.swift
```
Missing argument for parameter 'localizedLabels' in call
```

<img width="1065" alt="Screen Shot 2020-04-22 at 10 44 34" src="https://user-images.githubusercontent.com/59780143/79996460-7ca69f00-8486-11ea-99f5-867fd3fad822.png">

**Comment by gabdsg** [comment]
> @lukasgit Got this error when compiling on Xcode
> 
> Version 0.4.2
> 
> # SwiftContactsServicePlugin.swift
> ```
> Missing argument for parameter 'localizedLabels' in call
> ```
> 
> <img alt="Screen Shot 2020-04-22 at 10 44 34" width="1065" src="https://user-images.githubusercontent.com/59780143/79996460-7ca69f00-8486-11ea-99f5-867fd3fad822.png">

Same problem

**Comment by lukasgit** [comment]
@sperochon see above posts Missing argument for parameter 'localizedLabels' in call

**Comment by sperochon** [comment]
Seems to forget some files... I look at it...

**Comment by lukasgit** [comment]
@sperochon thank you

**Comment by lukasgit** [comment]
@sperochon also note the latest PR #94

**Comment by pavanbuzz** [comment]
> @sperochon see above posts Missing argument for parameter 'localizedLabels' in call

I have fixed it in my [code PR 94](https://github.com/lukasgit/flutter_contacts/pull/94)

**Comment by sperochon** [comment]
I have added the parameter missing iOSLocalizedLabels parameter to new methods openContactForm and openExistingContact.
The PR is #96

**Comment by lukasgit** [comment]
PR #96 now included in version 0.4.4
