### ISSUE TITLE
Problems with adding mobile number

### ISSUE THREAD

**Issue by Dfisch3r** [lukasgit/flutter_contacts#86]
I am able to add a phone number like this:
`contact.phones = [Item(label: "work", value: telephone)];}`
and it works. But when I try to add a mobile number, it doesn't work
`contact.phones = [Item(label: "mobile", value: mobil)];}`

Does anybody knows how to fix this?

Thanks!

**Comment by pavanbuzz** [comment]
If you could share error log, we might be able to help you. As adding mobile number works as expected.

**Comment by Dfisch3r** [comment]
@pavanbuzz thanks for your reply! 
I do not get an error, but while testing I found out, that if I want to to add just a mobile number, everything works fine. But if I want to create an contact with both numbers, just the last one will be added. So if I first add the mobile number and than the work number, the work number will be saved, and if i first add the work number and than the mobile number, the mobile number will be saved.
Do you know how I could solve this? I just implement the numbers like I said in my first message.

**Comment by pavanbuzz** [comment]
@Dfisch3r Phones, Emails, Postal Addresses are lists. Hence in your version of the code you were replacing the items that were previously added. 
```
Iterable<Item> emails = [];
Iterable<Item> phones = [];
Iterable<PostalAddress> postalAddresses = [];
```
The above code was extracted from [Code Link](https://github.com/lukasgit/flutter_contacts/blob/34d9eaec70fd4b64dc1253ac80d1dd2fab0f0668/lib/contacts_service.dart#L158-L160)

In your case, change the code to `contact.phones = [Item(label: "work", value: telephone), Item(label: "mobile", value: mobile)];`

**Comment by Dfisch3r** [comment]
@pavanbuzz Oh! Thanks that worked! 
But now I run into another problem (I think that haven't accured before). If I want to add a new contact with the same name, the (new) informations just get add to the old contact. But I do not use .updateContact, I use `await ContactsService.addContact(contact);  ` 
How can I force to always add a new contact, even if there exist a similar contact?

**Comment by pavanbuzz** [comment]
As per [Apple's Documentation for CNSaveRequest](https://developer.apple.com/documentation/contacts/cnsaverequest);
```
If you try to add an object (that is, a contact or a group) that already exists in the contact store, you receive the CNError.Code.insertedRecordAlreadyExists error and the CNErrorUserInfoAffectedRecordsKey array is updated to contain the object you tried to add.
``` 
To answer your question, iOS will throw an error if the contact already exists in the contact store.

**Comment by Dfisch3r** [comment]
@pavanbuzz but isn't it possible to add two contacts with the same name? Maybe someone knows two guys called "Max Anderson".

**Comment by Dfisch3r** [comment]
Solved.
Thanks for your help!
