### ISSUE TITLE
Unable to retrieve contacts by email

### ISSUE THREAD

**Issue by pavanbuzz** [lukasgit/flutter_contacts#93]
After the recent introduction of iOSLocalizedLabels, getContactsForEmail stopped working.

**Comment by lukasgit** [comment]
@sperochon @pavanbuzz can either of you look into this?

**Comment by pavanbuzz** [comment]
@lukasgit  - PR for the issue

**Comment by lukasgit** [comment]
@pavanbuzz merged PR #94 . If the problem persists please re-open this issue. Thanks :-)
